import type { Pillar, Process, Framework, PillarId } from './types';

export const PILLARS: Pillar[] = [
  {
    id: 'P1',
    name: 'Gouvernance & Leadership',
    description: 'Pilotage strategique de la cybersecurite au niveau direction',
    processCount: 15,
    weight: 0.20,
  },
  {
    id: 'P2',
    name: 'Gestion des Risques Cyber',
    description: 'Identification, evaluation et traitement des risques',
    processCount: 16,
    weight: 0.18,
  },
  {
    id: 'P3',
    name: 'Conformite & Reglementation',
    description: 'Conformite aux exigences reglementaires et normatives',
    processCount: 14,
    weight: 0.12,
  },
  {
    id: 'P4',
    name: 'Securite Operationnelle',
    description: 'Mesures de securite techniques et operationnelles',
    processCount: 18,
    weight: 0.15,
  },
  {
    id: 'P5',
    name: 'Resilience & Continuite',
    description: 'Capacite de reprise et continuite des activites',
    processCount: 13,
    weight: 0.12,
  },
  {
    id: 'P6',
    name: 'Gestion des Tiers (TPRM)',
    description: 'Securite de la chaine de sous-traitance',
    processCount: 14,
    weight: 0.08,
  },
  {
    id: 'P7',
    name: 'Protection des Donnees',
    description: 'Protection et confidentialite des donnees',
    processCount: 15,
    weight: 0.07,
  },
  {
    id: 'P8',
    name: 'Innovation & Transformation',
    description: 'Integration de la securite dans la transformation digitale',
    processCount: 15,
    weight: 0.08,
  },
];

export const PROCESSES: Process[] = [
  {
    id: 'P1.G.001',
    pillarId: 'P1',
    name: 'Strategie cybersecurite',
    description: 'Definition et revision de la strategie cybersecurite alignee sur les objectifs metiers',
    objective: 'Disposer d\'une strategie cybersecurite formalisee et approuvee par la direction',
    maturityCriteria: {
      1: ['Pas de strategie formalisee'],
      2: ['Strategie informelle ou partielle'],
      3: ['Strategie documentee et communiquee'],
      4: ['Strategie revisee annuellement avec KPIs'],
      5: ['Strategie integree et pilotee en temps reel'],
    },
    regulatoryMappings: { iso27001: ['5.1', '5.2'], nis2: ['Art. 21(2)(a)'], dora: ['Art. 5'] },
  },
  {
    id: 'P1.G.002',
    pillarId: 'P1',
    name: 'Gouvernance et organisation',
    description: 'Structure organisationnelle de la fonction cybersecurite',
    objective: 'Disposer d\'une organisation claire avec des roles et responsabilites definis',
    maturityCriteria: {
      1: ['Aucune organisation formelle'],
      2: ['RSSI designe, perimetre flou'],
      3: ['Organisation documentee, RACI defini'],
      4: ['Comites reguliers, reporting direction'],
      5: ['Organisation agile, gouvernance integree'],
    },
    regulatoryMappings: { iso27001: ['5.3', '7.1'], nis2: ['Art. 21(2)(a)'] },
  },
  {
    id: 'P1.G.003',
    pillarId: 'P1',
    name: 'Budget et ressources',
    description: 'Allocation des ressources financieres et humaines',
    objective: 'Disposer de ressources adequates pour la cybersecurite',
    maturityCriteria: {
      1: ['Budget non identifie'],
      2: ['Budget ad-hoc sur projets'],
      3: ['Budget dedie annuel'],
      4: ['Budget pluriannuel avec ROI'],
      5: ['Budget optimise, benchmark sectoriel'],
    },
    regulatoryMappings: { iso27001: ['7.1'], nis2: ['Art. 21(2)(h)'] },
  },
  {
    id: 'P1.G.004',
    pillarId: 'P1',
    name: 'Politiques de securite',
    description: 'Corpus documentaire des politiques de securite',
    objective: 'Disposer de politiques couvrant tous les domaines de securite',
    maturityCriteria: {
      1: ['Aucune politique formalisee'],
      2: ['Politique generale uniquement'],
      3: ['Politiques thematiques completes'],
      4: ['Politiques revues, diffusees, controlees'],
      5: ['Politiques adaptatives, integrees aux processus'],
    },
    regulatoryMappings: { iso27001: ['5.1', 'A.5.1'], nis2: ['Art. 21(2)(a)'] },
  },
  {
    id: 'P1.G.005',
    pillarId: 'P1',
    name: 'Comite de pilotage cyber',
    description: 'Instance de gouvernance dediee a la cybersecurite',
    objective: 'Piloter la cybersecurite au niveau direction',
    maturityCriteria: {
      1: ['Aucun comite'],
      2: ['Reunions ad-hoc'],
      3: ['Comite trimestriel avec compte-rendu'],
      4: ['Comite mensuel, indicateurs suivis'],
      5: ['Comite integre aux instances strategiques'],
    },
    regulatoryMappings: { iso27001: ['5.1'], nis2: ['Art. 20'] },
  },
  {
    id: 'P2.R.001',
    pillarId: 'P2',
    name: 'Cartographie des actifs',
    description: 'Inventaire exhaustif des actifs informationnels et systemes',
    objective: 'Connaitre l\'ensemble des actifs a proteger',
    maturityCriteria: {
      1: ['Pas d\'inventaire'],
      2: ['Inventaire partiel ou obsolete'],
      3: ['Inventaire complet et maintenu'],
      4: ['Inventaire automatise avec valorisation'],
      5: ['CMDB temps reel, integree aux outils'],
    },
    regulatoryMappings: { iso27001: ['A.5.9'], nis2: ['Art. 21(2)(b)'], dora: ['Art. 8'] },
  },
  {
    id: 'P2.R.002',
    pillarId: 'P2',
    name: 'Analyse de risques',
    description: 'Methodologie d\'analyse et d\'evaluation des risques cyber',
    objective: 'Identifier et evaluer les risques de maniere systematique',
    maturityCriteria: {
      1: ['Aucune analyse formelle'],
      2: ['Analyses ponctuelles, non methodiques'],
      3: ['Methodologie definie (EBIOS RM, ISO 27005)'],
      4: ['Analyses periodiques, quantifiees'],
      5: ['Analyse continue, integree aux processus'],
    },
    regulatoryMappings: { iso27001: ['6.1', '8.2'], nis2: ['Art. 21(2)(b)'], dora: ['Art. 6'] },
  },
  {
    id: 'P2.R.003',
    pillarId: 'P2',
    name: 'Traitement des risques',
    description: 'Plans de traitement et suivi des risques identifies',
    objective: 'Traiter les risques selon l\'appetence definie',
    maturityCriteria: {
      1: ['Pas de traitement formalise'],
      2: ['Traitement reactif au cas par cas'],
      3: ['Plans de traitement documentes'],
      4: ['Suivi regulier, indicateurs d\'efficacite'],
      5: ['Optimisation continue, arbitrage dynamique'],
    },
    regulatoryMappings: { iso27001: ['6.1.3', '8.3'], nis2: ['Art. 21(2)(b)'] },
  },
  {
    id: 'P2.R.004',
    pillarId: 'P2',
    name: 'Veille en vulnerabilites',
    description: 'Surveillance des vulnerabilites affectant les systemes',
    objective: 'Anticiper les menaces par la veille',
    maturityCriteria: {
      1: ['Pas de veille structuree'],
      2: ['Veille manuelle occasionnelle'],
      3: ['Abonnements CERT, process defini'],
      4: ['Veille automatisee, correlation assets'],
      5: ['Threat intelligence integree'],
    },
    regulatoryMappings: { iso27001: ['A.5.7'], nis2: ['Art. 21(2)(e)'] },
  },
  {
    id: 'P2.R.005',
    pillarId: 'P2',
    name: 'Gestion des vulnerabilites',
    description: 'Processus de detection et remediation des vulnerabilites',
    objective: 'Maintenir un niveau de vulnerabilite acceptable',
    maturityCriteria: {
      1: ['Pas de scan de vulnerabilites'],
      2: ['Scans ponctuels'],
      3: ['Scans reguliers, process de patch'],
      4: ['SLA de remediation, mesure conformite'],
      5: ['Automatisation complete, zero-day process'],
    },
    regulatoryMappings: { iso27001: ['A.8.8'], nis2: ['Art. 21(2)(e)'], dora: ['Art. 10'] },
  },
  {
    id: 'P3.C.001',
    pillarId: 'P3',
    name: 'Veille reglementaire',
    description: 'Suivi des evolutions reglementaires applicables',
    objective: 'Anticiper les obligations reglementaires',
    maturityCriteria: {
      1: ['Pas de veille reglementaire'],
      2: ['Veille informelle'],
      3: ['Veille structuree, responsable identifie'],
      4: ['Analyse d\'impact systematique'],
      5: ['Veille automatisee, anticipation'],
    },
    regulatoryMappings: { iso27001: ['4.2'], nis2: ['Art. 21'], dora: ['Art. 4'] },
  },
  {
    id: 'P3.C.002',
    pillarId: 'P3',
    name: 'Conformite ISO 27001',
    description: 'Mise en conformite avec la norme ISO 27001:2022',
    objective: 'Atteindre et maintenir la certification ISO 27001',
    maturityCriteria: {
      1: ['Non engage'],
      2: ['Gap analysis realisee'],
      3: ['SMSI documente et operationnel'],
      4: ['Certifie, audits internes reguliers'],
      5: ['Amelioration continue demontree'],
    },
    regulatoryMappings: { iso27001: ['All'], nis2: ['Art. 21(2)(j)'] },
  },
  {
    id: 'P3.C.003',
    pillarId: 'P3',
    name: 'Conformite NIS2',
    description: 'Conformite a la directive europeenne NIS2',
    objective: 'Respecter les exigences NIS2 avant echeance',
    maturityCriteria: {
      1: ['Non evalue'],
      2: ['Perimetre identifie'],
      3: ['Plan de mise en conformite'],
      4: ['Mesures implementees'],
      5: ['Conformite totale, auditable'],
    },
    regulatoryMappings: { nis2: ['Art. 20-23'] },
  },
  {
    id: 'P3.C.004',
    pillarId: 'P3',
    name: 'Conformite DORA',
    description: 'Conformite au reglement DORA pour le secteur financier',
    objective: 'Respecter les exigences DORA',
    maturityCriteria: {
      1: ['Non applicable ou non evalue'],
      2: ['Gap analysis initiale'],
      3: ['Cadre de resilience documente'],
      4: ['Tests de resilience realises'],
      5: ['Conformite complete, reporting ACPR'],
    },
    regulatoryMappings: { dora: ['All'] },
  },
  {
    id: 'P3.C.005',
    pillarId: 'P3',
    name: 'Audit interne cyber',
    description: 'Programme d\'audits internes de securite',
    objective: 'Controler l\'application des mesures de securite',
    maturityCriteria: {
      1: ['Pas d\'audit interne'],
      2: ['Audits ponctuels'],
      3: ['Programme annuel d\'audits'],
      4: ['Suivi des non-conformites, KPIs'],
      5: ['Audit continu, assurance qualite'],
    },
    regulatoryMappings: { iso27001: ['9.2'], nis2: ['Art. 21(2)(j)'] },
  },
  {
    id: 'P4.O.001',
    pillarId: 'P4',
    name: 'Gestion des acces',
    description: 'Controle des acces logiques aux systemes',
    objective: 'Garantir que seuls les utilisateurs autorises accedent aux ressources',
    maturityCriteria: {
      1: ['Gestion basique des comptes'],
      2: ['Politique de mots de passe'],
      3: ['IAM centralise, RBAC'],
      4: ['MFA generalise, revues d\'acces'],
      5: ['Zero Trust, acces adaptatif'],
    },
    regulatoryMappings: { iso27001: ['A.5.15', 'A.5.16', 'A.5.18'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 9'] },
  },
  {
    id: 'P4.O.002',
    pillarId: 'P4',
    name: 'Securite reseau',
    description: 'Protection du reseau et segmentation',
    objective: 'Proteger l\'infrastructure reseau des menaces',
    maturityCriteria: {
      1: ['Reseau plat, firewall basique'],
      2: ['DMZ, regles firewall documentees'],
      3: ['Segmentation, IDS/IPS'],
      4: ['Micro-segmentation, NDR'],
      5: ['Software-defined security, automatisation'],
    },
    regulatoryMappings: { iso27001: ['A.8.20', 'A.8.21'], nis2: ['Art. 21(2)(c)'] },
  },
  {
    id: 'P4.O.003',
    pillarId: 'P4',
    name: 'Protection endpoint',
    description: 'Securisation des postes de travail et terminaux',
    objective: 'Proteger les endpoints contre les menaces',
    maturityCriteria: {
      1: ['Antivirus basique'],
      2: ['Antivirus centralise, mises a jour'],
      3: ['EDR deploye'],
      4: ['EDR avec reponse automatisee'],
      5: ['XDR integre, threat hunting'],
    },
    regulatoryMappings: { iso27001: ['A.8.1', 'A.8.7'], nis2: ['Art. 21(2)(c)'] },
  },
  {
    id: 'P4.O.004',
    pillarId: 'P4',
    name: 'Supervision de securite (SOC)',
    description: 'Surveillance et detection des incidents de securite',
    objective: 'Detecter les incidents de securite rapidement',
    maturityCriteria: {
      1: ['Pas de supervision centralisee'],
      2: ['Logs collectes, analyse manuelle'],
      3: ['SIEM operationnel, use cases'],
      4: ['SOC 24/7, SLA de detection'],
      5: ['SOC avance, SOAR, ML'],
    },
    regulatoryMappings: { iso27001: ['A.8.15', 'A.8.16'], nis2: ['Art. 21(2)(c)'], dora: ['Art. 10'] },
  },
  {
    id: 'P4.O.005',
    pillarId: 'P4',
    name: 'Gestion des incidents',
    description: 'Processus de reponse aux incidents de securite',
    objective: 'Repondre efficacement aux incidents',
    maturityCriteria: {
      1: ['Pas de processus formalise'],
      2: ['Procedure basique de reponse'],
      3: ['Processus documente, equipe identifiee'],
      4: ['Playbooks, exercices reguliers'],
      5: ['Automatisation SOAR, amelioration continue'],
    },
    regulatoryMappings: { iso27001: ['A.5.24', 'A.5.25', 'A.5.26'], nis2: ['Art. 21(2)(c)', 'Art. 23'], dora: ['Art. 17'] },
  },
  {
    id: 'P5.B.001',
    pillarId: 'P5',
    name: 'Plan de continuite (PCA)',
    description: 'Plan de continuite des activites metiers',
    objective: 'Assurer la continuite des activites critiques',
    maturityCriteria: {
      1: ['Pas de PCA'],
      2: ['PCA partiel ou obsolete'],
      3: ['PCA documente, BIA realise'],
      4: ['PCA teste annuellement'],
      5: ['PCA integre, resilience prouvee'],
    },
    regulatoryMappings: { iso27001: ['A.5.29', 'A.5.30'], nis2: ['Art. 21(2)(c)'], dora: ['Art. 11', 'Art. 12'] },
  },
  {
    id: 'P5.B.002',
    pillarId: 'P5',
    name: 'Plan de reprise (PRA)',
    description: 'Plan de reprise d\'activite apres sinistre',
    objective: 'Permettre la reprise des systemes critiques',
    maturityCriteria: {
      1: ['Pas de PRA'],
      2: ['Sauvegardes basiques'],
      3: ['PRA documente, RTO/RPO definis'],
      4: ['PRA teste, site de secours'],
      5: ['Reprise automatisee, exercices'],
    },
    regulatoryMappings: { iso27001: ['A.5.30'], nis2: ['Art. 21(2)(c)'], dora: ['Art. 12'] },
  },
  {
    id: 'P5.B.003',
    pillarId: 'P5',
    name: 'Sauvegardes',
    description: 'Politique et processus de sauvegarde des donnees',
    objective: 'Garantir la disponibilite des donnees',
    maturityCriteria: {
      1: ['Sauvegardes non systematiques'],
      2: ['Sauvegardes regulieres'],
      3: ['Politique 3-2-1, tests de restauration'],
      4: ['Sauvegardes immuables, chiffrees'],
      5: ['Sauvegarde continue, air-gap'],
    },
    regulatoryMappings: { iso27001: ['A.8.13'], nis2: ['Art. 21(2)(c)'], dora: ['Art. 12'] },
  },
  {
    id: 'P5.B.004',
    pillarId: 'P5',
    name: 'Gestion de crise cyber',
    description: 'Dispositif de gestion de crise en cas d\'incident majeur',
    objective: 'Gerer efficacement les crises cyber',
    maturityCriteria: {
      1: ['Pas de dispositif'],
      2: ['Contacts d\'urgence identifies'],
      3: ['Cellule de crise, procedures'],
      4: ['Exercices de crise annuels'],
      5: ['Cellule rodee, communication de crise'],
    },
    regulatoryMappings: { iso27001: ['A.5.24'], nis2: ['Art. 21(2)(c)'], dora: ['Art. 17'] },
  },
  {
    id: 'P5.B.005',
    pillarId: 'P5',
    name: 'Tests de resilience',
    description: 'Tests reguliers des capacites de resilience',
    objective: 'Valider l\'efficacite des plans de resilience',
    maturityCriteria: {
      1: ['Pas de tests'],
      2: ['Tests ponctuels'],
      3: ['Programme de tests annuel'],
      4: ['Tests realistes, retex formalise'],
      5: ['Tests continus, chaos engineering'],
    },
    regulatoryMappings: { iso27001: ['A.5.30'], dora: ['Art. 26', 'Art. 27'] },
  },
  {
    id: 'P6.T.001',
    pillarId: 'P6',
    name: 'Inventaire des tiers',
    description: 'Cartographie des fournisseurs et prestataires',
    objective: 'Connaitre l\'ensemble de la chaine de sous-traitance',
    maturityCriteria: {
      1: ['Pas d\'inventaire des tiers'],
      2: ['Liste partielle des fournisseurs'],
      3: ['Inventaire complet avec criticite'],
      4: ['Inventaire dynamique, dependances'],
      5: ['Chaine de valeur cartographiee'],
    },
    regulatoryMappings: { iso27001: ['A.5.19'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 28'] },
  },
  {
    id: 'P6.T.002',
    pillarId: 'P6',
    name: 'Due diligence securite',
    description: 'Evaluation de securite des tiers avant contractualisation',
    objective: 'S\'assurer de la maturite securite des tiers',
    maturityCriteria: {
      1: ['Pas d\'evaluation'],
      2: ['Questionnaire basique'],
      3: ['Due diligence formalisee'],
      4: ['Scoring securite, rating externe'],
      5: ['Evaluation continue, audit sur site'],
    },
    regulatoryMappings: { iso27001: ['A.5.20'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 28'] },
  },
  {
    id: 'P6.T.003',
    pillarId: 'P6',
    name: 'Clauses contractuelles',
    description: 'Exigences de securite dans les contrats',
    objective: 'Imposer des obligations de securite aux tiers',
    maturityCriteria: {
      1: ['Pas de clauses specifiques'],
      2: ['Clauses generiques'],
      3: ['Clauses adaptees au risque'],
      4: ['SLA securite, penalites'],
      5: ['Clauses dynamiques, droit d\'audit'],
    },
    regulatoryMappings: { iso27001: ['A.5.20'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 30'] },
  },
  {
    id: 'P6.T.004',
    pillarId: 'P6',
    name: 'Surveillance des tiers',
    description: 'Suivi continu de la posture securite des tiers',
    objective: 'Maintenir la visibilite sur les risques tiers',
    maturityCriteria: {
      1: ['Pas de surveillance'],
      2: ['Revue annuelle manuelle'],
      3: ['Surveillance trimestrielle'],
      4: ['Monitoring continu, alertes'],
      5: ['Integration SOC, threat intelligence'],
    },
    regulatoryMappings: { iso27001: ['A.5.22'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 28'] },
  },
  {
    id: 'P6.T.005',
    pillarId: 'P6',
    name: 'Gestion des incidents tiers',
    description: 'Processus de notification et gestion des incidents impliquant des tiers',
    objective: 'Reagir aux incidents de securite des tiers',
    maturityCriteria: {
      1: ['Pas de processus'],
      2: ['Notification contractuelle'],
      3: ['Processus de coordination'],
      4: ['Exercices conjoints'],
      5: ['Chaine d\'incident integree'],
    },
    regulatoryMappings: { iso27001: ['A.5.21'], nis2: ['Art. 21(2)(d)'] },
  },
  {
    id: 'P7.D.001',
    pillarId: 'P7',
    name: 'Classification des donnees',
    description: 'Schema de classification et marquage des donnees',
    objective: 'Identifier et proteger les donnees selon leur sensibilite',
    maturityCriteria: {
      1: ['Pas de classification'],
      2: ['Classification informelle'],
      3: ['Schema formalise, marquage'],
      4: ['Classification automatisee'],
      5: ['DLP integre, gouvernance data'],
    },
    regulatoryMappings: { iso27001: ['A.5.12', 'A.5.13'], rgpd: ['Art. 5'], nis2: ['Art. 21(2)(b)'] },
  },
  {
    id: 'P7.D.002',
    pillarId: 'P7',
    name: 'Chiffrement',
    description: 'Protection cryptographique des donnees sensibles',
    objective: 'Garantir la confidentialite des donnees',
    maturityCriteria: {
      1: ['Pas de chiffrement'],
      2: ['Chiffrement partiel'],
      3: ['Chiffrement at-rest et in-transit'],
      4: ['Gestion des cles centralisee'],
      5: ['Chiffrement de bout en bout, HSM'],
    },
    regulatoryMappings: { iso27001: ['A.8.24'], rgpd: ['Art. 32'], dora: ['Art. 9'] },
  },
  {
    id: 'P7.D.003',
    pillarId: 'P7',
    name: 'Conformite RGPD',
    description: 'Mise en conformite avec le RGPD',
    objective: 'Respecter les obligations du RGPD',
    maturityCriteria: {
      1: ['Non conforme'],
      2: ['Registre des traitements initie'],
      3: ['DPO, procedures, PIA'],
      4: ['Privacy by design, audits'],
      5: ['Conformite demontree, culture privacy'],
    },
    regulatoryMappings: { rgpd: ['All'] },
  },
  {
    id: 'P7.D.004',
    pillarId: 'P7',
    name: 'Gestion des droits',
    description: 'Processus de gestion des droits des personnes concernees',
    objective: 'Permettre l\'exercice des droits RGPD',
    maturityCriteria: {
      1: ['Pas de processus'],
      2: ['Traitement manuel au cas par cas'],
      3: ['Procedures documentees'],
      4: ['Portail self-service'],
      5: ['Automatisation, tracabilite complete'],
    },
    regulatoryMappings: { rgpd: ['Art. 15-22'] },
  },
  {
    id: 'P7.D.005',
    pillarId: 'P7',
    name: 'Notification de violation',
    description: 'Processus de notification des violations de donnees',
    objective: 'Respecter les delais de notification RGPD',
    maturityCriteria: {
      1: ['Pas de processus'],
      2: ['Procedure basique'],
      3: ['Processus 72h documente'],
      4: ['Exercices de notification'],
      5: ['Detection automatisee, reporting'],
    },
    regulatoryMappings: { rgpd: ['Art. 33', 'Art. 34'], nis2: ['Art. 23'] },
  },
  {
    id: 'P8.I.001',
    pillarId: 'P8',
    name: 'Security by Design',
    description: 'Integration de la securite des la conception des projets',
    objective: 'Integrer la securite dans le cycle de developpement',
    maturityCriteria: {
      1: ['Securite en fin de projet'],
      2: ['Revues securite ponctuelles'],
      3: ['Security champions, guidelines'],
      4: ['DevSecOps, shift-left'],
      5: ['Securite native, automatisee'],
    },
    regulatoryMappings: { iso27001: ['A.8.25'], rgpd: ['Art. 25'] },
  },
  {
    id: 'P8.I.002',
    pillarId: 'P8',
    name: 'Securite Cloud',
    description: 'Gouvernance de la securite des environnements cloud',
    objective: 'Maitriser les risques lies au cloud',
    maturityCriteria: {
      1: ['Shadow IT, cloud non gouverne'],
      2: ['Politique cloud basique'],
      3: ['CASB, gouvernance multi-cloud'],
      4: ['CSPM, conformite automatisee'],
      5: ['Cloud security maturity complete'],
    },
    regulatoryMappings: { iso27001: ['A.5.23'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 28'] },
  },
  {
    id: 'P8.I.003',
    pillarId: 'P8',
    name: 'Securite applicative',
    description: 'Securisation du developpement logiciel',
    objective: 'Produire des applications securisees',
    maturityCriteria: {
      1: ['Pas de pratiques SSDLC'],
      2: ['Tests de securite ponctuels'],
      3: ['SAST/DAST integres'],
      4: ['Pipeline securise, SBOM'],
      5: ['DevSecOps mature, SCA continu'],
    },
    regulatoryMappings: { iso27001: ['A.8.25', 'A.8.26', 'A.8.27'], dora: ['Art. 10'] },
  },
  {
    id: 'P8.I.004',
    pillarId: 'P8',
    name: 'Securite IA/ML',
    description: 'Gouvernance de la securite des systemes d\'IA',
    objective: 'Maitriser les risques lies a l\'IA',
    maturityCriteria: {
      1: ['Pas de gouvernance IA'],
      2: ['Sensibilisation aux risques'],
      3: ['Politique IA, inventaire modeles'],
      4: ['Tests adversariaux, monitoring'],
      5: ['AI security mature, conformite AI Act'],
    },
    regulatoryMappings: {},
  },
  {
    id: 'P8.I.005',
    pillarId: 'P8',
    name: 'Veille technologique',
    description: 'Suivi des tendances et menaces emergentes',
    objective: 'Anticiper les evolutions technologiques',
    maturityCriteria: {
      1: ['Pas de veille structuree'],
      2: ['Veille informelle'],
      3: ['Veille organisee, partage interne'],
      4: ['R&D securite, POC reguliers'],
      5: ['Innovation securite, contributions'],
    },
    regulatoryMappings: { iso27001: ['A.5.7'] },
  },
// ── P1 extra (G.006 → G.015) ─────────────────────────
  { id: 'P1.G.006', pillarId: 'P1', name: 'Sensibilisation et formation', description: 'Programme de sensibilisation des collaborateurs à la cybersécurité', objective: 'Développer une culture cybersécurité à tous les niveaux', maturityCriteria: { 1: ['Pas de sensibilisation'], 2: ['Formations ponctuelles'], 3: ['Programme annuel formalisé'], 4: ['Formation ciblée par rôle, e-learning'], 5: ['Culture cyber ancrée, mesures d\'efficacité'] }, regulatoryMappings: { iso27001: ['6.3', '7.2', '7.3'], nis2: ['Art. 21(2)(g)'] } },
  { id: 'P1.G.007', pillarId: 'P1', name: 'Reporting direction', description: 'Tableau de bord et reporting vers la direction générale', objective: 'Informer la direction sur la posture de sécurité', maturityCriteria: { 1: ['Aucun reporting'], 2: ['Reporting annuel informel'], 3: ['Reporting trimestriel structuré'], 4: ['Dashboard temps réel'], 5: ['Reporting intégré à la gouvernance d\'entreprise'] }, regulatoryMappings: { iso27001: ['9.3'], nis2: ['Art. 20(1)'] } },
  { id: 'P1.G.008', pillarId: 'P1', name: 'Gestion documentaire', description: 'Cycle de vie des documents et politiques de sécurité', objective: 'Maintenir une documentation à jour et accessible', maturityCriteria: { 1: ['Documentation inexistante'], 2: ['Documents non versionnés'], 3: ['GED structurée, cycle de révision'], 4: ['Workflow d\'approbation, traçabilité'], 5: ['Documentation automatisée'] }, regulatoryMappings: { iso27001: ['7.5'] } },
  { id: 'P1.G.009', pillarId: 'P1', name: 'Conformité légale et réglementaire', description: 'Veille et gestion de la conformité aux obligations légales', objective: 'Identifier et respecter toutes les obligations réglementaires applicables', maturityCriteria: { 1: ['Pas de veille réglementaire'], 2: ['Veille ponctuelle non structurée'], 3: ['Registre des obligations, responsables désignés'], 4: ['Plan de conformité, suivi des échéances'], 5: ['Conformité en temps réel, audit automatisé'] }, regulatoryMappings: { iso27001: ['5.31', '5.32', '5.33', '5.34'], nis2: ['Art. 21'], dora: ['Art. 5'] } },
  { id: 'P1.G.010', pillarId: 'P1', name: 'Métriques et indicateurs (KRI/KPI)', description: 'Définition et suivi des indicateurs clés de risque et de performance', objective: 'Mesurer objectivement la performance de la cybersécurité', maturityCriteria: { 1: ['Pas d\'indicateurs'], 2: ['Quelques métriques ad-hoc'], 3: ['KPI/KRI définis et suivis'], 4: ['Tableaux de bord automatisés'], 5: ['Intelligence des métriques, benchmarking sectoriel'] }, regulatoryMappings: { iso27001: ['9.1'], nis2: ['Art. 21(2)(a)'] } },
  { id: 'P1.G.011', pillarId: 'P1', name: 'Audit interne cybersécurité', description: 'Programme d\'audit interne des contrôles de sécurité', objective: 'Évaluer indépendamment l\'efficacité des contrôles', maturityCriteria: { 1: ['Pas d\'audit interne'], 2: ['Audits ponctuels non planifiés'], 3: ['Programme d\'audit annuel structuré'], 4: ['Audits risque-based'], 5: ['Audit continu, automatisation des contrôles'] }, regulatoryMappings: { iso27001: ['9.2'], nis2: ['Art. 21(2)(h)'], dora: ['Art. 17'] } },
  { id: 'P1.G.012', pillarId: 'P1', name: 'Relations avec les autorités', description: 'Gestion des relations avec les régulateurs et autorités compétentes', objective: 'Maintenir des relations constructives avec les superviseurs', maturityCriteria: { 1: ['Aucune relation établie'], 2: ['Contacts ad-hoc en cas d\'incident'], 3: ['Points de contact désignés'], 4: ['Dialogue régulier, groupes de travail'], 5: ['Partenariat stratégique'] }, regulatoryMappings: { iso27001: ['5.32'], nis2: ['Art. 27', 'Art. 29'], dora: ['Art. 7'] } },
  { id: 'P1.G.013', pillarId: 'P1', name: 'Gestion des exceptions', description: 'Processus formel de gestion des exceptions aux politiques de sécurité', objective: 'Contrôler et tracer les dérogations', maturityCriteria: { 1: ['Pas de processus d\'exception'], 2: ['Exceptions accordées informellement'], 3: ['Processus formalisé, validation obligatoire'], 4: ['Suivi des exceptions, revue périodique'], 5: ['Gestion automatisée, analyse de risque systématique'] }, regulatoryMappings: { iso27001: ['5.1'] } },
  { id: 'P1.G.014', pillarId: 'P1', name: 'Propriété des actifs', description: 'Attribution de propriétaires pour chaque actif critique', objective: 'S\'assurer que tout actif critique a un propriétaire responsable', maturityCriteria: { 1: ['Pas de notion de propriété'], 2: ['Propriétaires désignés informellement'], 3: ['Registre des propriétaires'], 4: ['Revue annuelle de propriété'], 5: ['Gouvernance des données intégrée'] }, regulatoryMappings: { iso27001: ['5.9', '5.10', '5.11'], rgpd: ['Art. 24'] } },
  { id: 'P1.G.015', pillarId: 'P1', name: 'Communication et transparence', description: 'Communication interne et externe sur les sujets cybersécurité', objective: 'Assurer une communication proactive et transparente', maturityCriteria: { 1: ['Communication inexistante'], 2: ['Communication réactive'], 3: ['Plan de communication structuré'], 4: ['Communication proactive, stakeholders intégrés'], 5: ['Transparence totale, reporting ESG'] }, regulatoryMappings: { iso27001: ['7.4'], nis2: ['Art. 23'] } },
  // ── P2 extra (R.006 → R.016) ─────────────────────────
  { id: 'P2.R.006', pillarId: 'P2', name: 'Registre des risques', description: 'Tenue et mise à jour du registre des risques cyber', objective: 'Centraliser tous les risques identifiés et leur traitement', maturityCriteria: { 1: ['Pas de registre'], 2: ['Liste informelle non maintenue'], 3: ['Registre structuré mis à jour régulièrement'], 4: ['Outil GRC dédié, workflow de validation'], 5: ['Registre dynamique intégré au pilotage'] }, regulatoryMappings: { iso27001: ['6.1.2', '8.2'], nis2: ['Art. 21(2)(a)'], dora: ['Art. 6'] } },
  { id: 'P2.R.007', pillarId: 'P2', name: 'Tests de pénétration', description: 'Programme de tests intrusifs sur les systèmes critiques', objective: 'Valider la résistance aux attaques par des tests offensifs', maturityCriteria: { 1: ['Jamais de pentest'], 2: ['Pentest ponctuel sur périmètre limité'], 3: ['Programme annuel structuré'], 4: ['Red team, TLPT pour entités financières'], 5: ['Purple team, tests continus, bug bounty'] }, regulatoryMappings: { iso27001: ['8.8'], dora: ['Art. 26', 'Art. 27'], nis2: ['Art. 21(2)(d)'] } },
  { id: 'P2.R.008', pillarId: 'P2', name: 'Gestion des risques sur projets', description: 'Intégration de l\'analyse de risques dans les projets et changements', objective: 'Évaluer l\'impact sécurité de tout nouveau projet ou changement', maturityCriteria: { 1: ['Pas d\'analyse de risque sur projets'], 2: ['Consultation sécurité ponctuelle'], 3: ['Revue de sécurité obligatoire en conception'], 4: ['Security by design systématique'], 5: ['Risk assessment automatisé dans le SDLC'] }, regulatoryMappings: { iso27001: ['6.1.2', '8.25', '8.26'], rgpd: ['Art. 25', 'Art. 35'] } },
  { id: 'P2.R.009', pillarId: 'P2', name: 'Appétence au risque', description: 'Définition et communication du niveau d\'acceptation du risque', objective: 'Aligner la prise de risque sur la stratégie', maturityCriteria: { 1: ['Pas d\'appétence définie'], 2: ['Seuils implicites non documentés'], 3: ['Risk appetite statement documenté'], 4: ['Appétence déclinée par catégorie'], 5: ['Risk appetite dynamique, lié aux objectifs'] }, regulatoryMappings: { iso27001: ['5.2', '6.1.1'], dora: ['Art. 6'] } },
  { id: 'P2.R.010', pillarId: 'P2', name: 'Cyber Threat Intelligence', description: 'Collecte, analyse et partage de renseignement sur les menaces', objective: 'Anticiper les menaces grâce à une intelligence proactive', maturityCriteria: { 1: ['Pas de CTI'], 2: ['Bulletins publics uniquement'], 3: ['CTI structurée, flux automatisés MISP'], 4: ['CTI opérationnelle, tactique, stratégique'], 5: ['Contribution aux ISAC, partage sectoriel'] }, regulatoryMappings: { nis2: ['Art. 21(2)(b)'], dora: ['Art. 13'] } },
  { id: 'P2.R.011', pillarId: 'P2', name: 'Scénarios de risque et impact', description: 'Développement et évaluation de scénarios de risque cyber', objective: 'Quantifier l\'impact potentiel des risques majeurs', maturityCriteria: { 1: ['Pas de scénarios'], 2: ['Scénarios génériques qualitatifs'], 3: ['Scénarios détaillés avec impact'], 4: ['Quantification financière (CRQ)'], 5: ['Modélisation probabiliste, Monte Carlo'] }, regulatoryMappings: { iso27001: ['6.1.2'], dora: ['Art. 8'] } },
  { id: 'P2.R.012', pillarId: 'P2', name: 'Gestion des risques OT/IoT', description: 'Sécurité des systèmes opérationnels et objets connectés', objective: 'Maîtriser les risques spécifiques aux environnements OT et IoT', maturityCriteria: { 1: ['Pas de considération OT/IoT'], 2: ['Inventaire partiel'], 3: ['Segmentation OT/IT, politique dédiée'], 4: ['Monitoring OT temps réel'], 5: ['Convergence IT/OT sécurisée'] }, regulatoryMappings: { nis2: ['Art. 21(2)(d)'] } },
  { id: 'P2.R.013', pillarId: 'P2', name: 'Assurance cyber', description: 'Évaluation et couverture du risque résiduel par l\'assurance', objective: 'Optimiser le transfert de risque résiduel', maturityCriteria: { 1: ['Pas d\'assurance cyber'], 2: ['Assurance générale'], 3: ['Police cyber dédiée, périmètre défini'], 4: ['Police alignée sur les risques quantifiés'], 5: ['Optimisation continue'] }, regulatoryMappings: { dora: ['Art. 6'] } },
  { id: 'P2.R.014', pillarId: 'P2', name: 'Analyse d\'impact (BIA)', description: 'Analyse d\'impact sur l\'activité en cas de cyber-incident', objective: 'Identifier les processus critiques et objectifs de reprise', maturityCriteria: { 1: ['Pas de BIA'], 2: ['BIA informel ou partiel'], 3: ['BIA complet, RTO/RPO définis'], 4: ['BIA intégré à la continuité'], 5: ['BIA dynamique mis à jour en continu'] }, regulatoryMappings: { nis2: ['Art. 21(2)(c)'], dora: ['Art. 11'], iso27001: ['8.2'] } },
  { id: 'P2.R.015', pillarId: 'P2', name: 'Revue périodique des risques', description: 'Processus de révision régulière du profil de risque', objective: 'S\'assurer que l\'évaluation des risques reste pertinente', maturityCriteria: { 1: ['Pas de revue systématique'], 2: ['Revue annuelle informelle'], 3: ['Revue semestrielle structurée'], 4: ['Revue déclenchée par événements'], 5: ['Cycle de vie du risque entièrement automatisé'] }, regulatoryMappings: { iso27001: ['9.3'], dora: ['Art. 6'] } },
  { id: 'P2.R.016', pillarId: 'P2', name: 'Exercices de crise cyber', description: 'Organisation d\'exercices et simulations de cyber-incidents', objective: 'Tester la capacité de réponse aux incidents par la pratique', maturityCriteria: { 1: ['Pas d\'exercice'], 2: ['Exercice de bureau annuel'], 3: ['Simulation réaliste multi-acteurs'], 4: ['Exercices red team vs blue team'], 5: ['Exercices continus, intégration de l\'écosystème'] }, regulatoryMappings: { nis2: ['Art. 21(2)(c)'], dora: ['Art. 26'] } },
  // ── P3 extra (C.006 → C.014) ─────────────────────────
  { id: 'P3.C.006', pillarId: 'P3', name: 'Gestion des audits externes', description: 'Préparation et gestion des audits réglementaires et de certification', objective: 'Répondre efficacement aux exigences des auditeurs', maturityCriteria: { 1: ['Pas de préparation'], 2: ['Préparation réactive avant audit'], 3: ['Programme de préparation structuré'], 4: ['Audit trail permanent'], 5: ['Audit readiness permanent, automatisé'] }, regulatoryMappings: { iso27001: ['9.2'], dora: ['Art. 17'], nis2: ['Art. 21'] } },
  { id: 'P3.C.007', pillarId: 'P3', name: 'Veille réglementaire', description: 'Surveillance des évolutions réglementaires et normatives', objective: 'Anticiper les changements réglementaires', maturityCriteria: { 1: ['Pas de veille'], 2: ['Veille manuelle irrégulière'], 3: ['Processus structuré, responsable désigné'], 4: ['Flux automatisés, alertes temps réel'], 5: ['Veille prédictive, participation aux consultations'] }, regulatoryMappings: { iso27001: ['5.32'] } },
  { id: 'P3.C.008', pillarId: 'P3', name: 'Gestion des preuves de conformité', description: 'Collection et conservation des preuves de conformité', objective: 'Démontrer la conformité à tout moment', maturityCriteria: { 1: ['Pas de collecte de preuves'], 2: ['Collecte ad-hoc mal organisée'], 3: ['Bibliothèque de preuves structurée'], 4: ['Collecte automatisée, horodatage'], 5: ['Preuves certifiées, chaîne de custody'] }, regulatoryMappings: { iso27001: ['9.1'], dora: ['Art. 17'] } },
  { id: 'P3.C.009', pillarId: 'P3', name: 'Notification aux autorités', description: 'Processus de notification des incidents significatifs aux régulateurs', objective: 'Respecter les délais et procédures de notification réglementaire', maturityCriteria: { 1: ['Pas de processus de notification'], 2: ['Notification ad-hoc, délais non respectés'], 3: ['Processus formalisé, seuils définis'], 4: ['Notification automatisée, traçabilité'], 5: ['Reporting proactif, dialogue régulier'] }, regulatoryMappings: { nis2: ['Art. 23'], dora: ['Art. 19', 'Art. 20'], rgpd: ['Art. 33', 'Art. 34'] } },
  { id: 'P3.C.010', pillarId: 'P3', name: 'Conformité contractuelle', description: 'Exigences de sécurité dans les contrats', objective: 'Intégrer les exigences de conformité dans tous les contrats', maturityCriteria: { 1: ['Pas de clauses sécurité'], 2: ['Clauses basiques dans certains contrats'], 3: ['Clauses standardisées'], 4: ['Conformité contractuelle auditée'], 5: ['Clauses dynamiques selon le risque'] }, regulatoryMappings: { iso27001: ['5.20', '5.21', '5.22'], dora: ['Art. 28', 'Art. 30'] } },
  { id: 'P3.C.011', pillarId: 'P3', name: 'Gestion des licences logicielles', description: 'Protection de la propriété intellectuelle et des licences', objective: 'Respecter les droits de PI et gérer les licences', maturityCriteria: { 1: ['Pas de gestion des licences'], 2: ['Inventaire partiel'], 3: ['Inventaire complet, processus de conformité'], 4: ['Gestion automatisée des licences'], 5: ['SBOM complet, conformité continue'] }, regulatoryMappings: { iso27001: ['5.32'] } },
  { id: 'P3.C.012', pillarId: 'P3', name: 'Certifications de sécurité', description: 'Obtention et maintien de certifications de sécurité', objective: 'Démontrer la maturité par des certifications reconnues', maturityCriteria: { 1: ['Aucune certification'], 2: ['Certification en projet'], 3: ['ISO 27001 ou équivalent obtenu'], 4: ['Plusieurs certifications maintenues'], 5: ['Certifications leaders, labels sectoriels'] }, regulatoryMappings: { nis2: ['Art. 24'] } },
  { id: 'P3.C.013', pillarId: 'P3', name: 'Transferts internationaux de données', description: 'Gestion des flux transfrontaliers de données personnelles', objective: 'Encadrer légalement les transferts de données hors UE', maturityCriteria: { 1: ['Pas d\'encadrement'], 2: ['Cartographie partielle'], 3: ['Mécanismes de transfert en place (CCT, BCR)'], 4: ['Audit régulier, alternatives aux transferts US'], 5: ['Localisation des données, conformité démontrée'] }, regulatoryMappings: { rgpd: ['Art. 44-49'] } },
  { id: 'P3.C.014', pillarId: 'P3', name: 'Conformité Cyber Resilience Act', description: 'Conformité au règlement CRA pour les produits numériques', objective: 'Préparer la conformité CRA', maturityCriteria: { 1: ['Pas de prise en compte du CRA'], 2: ['Périmètre d\'applicabilité évalué'], 3: ['Programme de conformité CRA'], 4: ['Documentation technique conforme'], 5: ['Conformité CRA complète, marquage CE cyber'] }, regulatoryMappings: { nis2: ['Art. 21(2)(d)'] } },
  // ── P4 extra (O.006 → O.018) ─────────────────────────
  { id: 'P4.O.006', pillarId: 'P4', name: 'Sécurité des emails', description: 'Protection contre le phishing et les attaques par email', objective: 'Réduire le risque d\'attaques via le vecteur email', maturityCriteria: { 1: ['Filtrage basique'], 2: ['Anti-spam, anti-malware'], 3: ['DMARC/DKIM/SPF, sandbox'], 4: ['Protection avancée anti-phishing'], 5: ['AI-based threat detection, formation continue'] }, regulatoryMappings: { iso27001: ['8.7', '8.23'], nis2: ['Art. 21(2)(d)'] } },
  { id: 'P4.O.007', pillarId: 'P4', name: 'Chiffrement des données', description: 'Protection cryptographique des données en transit et au repos', objective: 'Garantir la confidentialité des données par le chiffrement', maturityCriteria: { 1: ['Pas de chiffrement'], 2: ['TLS en transit uniquement'], 3: ['Chiffrement at-rest et in-transit'], 4: ['Gestion des clés centralisée (HSM/KMS)'], 5: ['Chiffrement E2E, post-quantum readiness'] }, regulatoryMappings: { iso27001: ['8.24'], rgpd: ['Art. 32'], nis2: ['Art. 21(2)(b)'], dora: ['Art. 9'] } },
  { id: 'P4.O.008', pillarId: 'P4', name: 'SIEM et détection des menaces', description: 'Centre de détection et réponse aux incidents (SOC/SIEM)', objective: 'Détecter en temps réel les comportements anormaux', maturityCriteria: { 1: ['Pas de SIEM ou SOC'], 2: ['SIEM basique, alertes simples'], 3: ['SIEM corrélé, SOC interne ou MSSP'], 4: ['SOC 24/7, UEBA, threat hunting'], 5: ['SOAR automatisé, réponse automatique'] }, regulatoryMappings: { iso27001: ['8.15', '8.16'], nis2: ['Art. 21(2)(b)'], dora: ['Art. 10'] } },
  { id: 'P4.O.009', pillarId: 'P4', name: 'Gestion des incidents de sécurité', description: 'Processus de réponse aux incidents de sécurité', objective: 'Répondre efficacement aux incidents pour minimiser l\'impact', maturityCriteria: { 1: ['Pas de processus d\'incident'], 2: ['Réponse ad-hoc non documentée'], 3: ['IRP formalisé, équipe dédiée'], 4: ['CSIRT/SOC opérationnel, runbooks'], 5: ['SOAR, retour d\'expérience systématique'] }, regulatoryMappings: { iso27001: ['5.24', '5.25', '5.26', '5.27'], nis2: ['Art. 23'], dora: ['Art. 17', 'Art. 18'] } },
  { id: 'P4.O.010', pillarId: 'P4', name: 'Sécurité physique', description: 'Contrôle d\'accès physique aux infrastructures critiques', objective: 'Protéger les actifs physiques contre les accès non autorisés', maturityCriteria: { 1: ['Pas de contrôle physique'], 2: ['Contrôles basiques (badges)'], 3: ['Zones de sécurité, journalisation'], 4: ['Surveillance vidéo, biométrie'], 5: ['Intégration physique-logique, monitoring temps réel'] }, regulatoryMappings: { iso27001: ['7.1', '7.2', '7.3', '7.4'], nis2: ['Art. 21(2)(d)'] } },
  { id: 'P4.O.011', pillarId: 'P4', name: 'Sauvegarde et restauration', description: 'Stratégie de sauvegarde et tests de restauration', objective: 'Garantir la disponibilité des données en cas d\'incident', maturityCriteria: { 1: ['Sauvegardes irrégulières'], 2: ['Sauvegardes régulières non testées'], 3: ['3-2-1 rule, tests réguliers'], 4: ['Sauvegardes immutables, RTO/RPO définis'], 5: ['Recovery automatisé, tests continus'] }, regulatoryMappings: { iso27001: ['8.13'], nis2: ['Art. 21(2)(c)'], dora: ['Art. 12'] } },
  { id: 'P4.O.012', pillarId: 'P4', name: 'Journalisation et monitoring', description: 'Collecte et analyse des journaux d\'événements système', objective: 'Maintenir une traçabilité complète des événements', maturityCriteria: { 1: ['Logs insuffisants ou non centralisés'], 2: ['Logs centralisés sans analyse'], 3: ['Politique de logging, rétention définie'], 4: ['Logs temps réel, corrélation automatique'], 5: ['Logging immutable, audit trail certifié'] }, regulatoryMappings: { iso27001: ['8.15', '8.16', '8.17'], nis2: ['Art. 21(2)(b)'], dora: ['Art. 10'] } },
  { id: 'P4.O.013', pillarId: 'P4', name: 'Gestion des configurations', description: 'Maîtrise des configurations de sécurité des systèmes', objective: 'Maintenir des configurations sécurisées sur tous les systèmes', maturityCriteria: { 1: ['Pas de baseline de configuration'], 2: ['Guides de configuration partiels'], 3: ['CIS Benchmarks appliqués, hardening'], 4: ['Gestion automatisée (IaC)'], 5: ['Configuration drift detection, auto-remédiation'] }, regulatoryMappings: { iso27001: ['8.9'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 9'] } },
  { id: 'P4.O.014', pillarId: 'P4', name: 'Sécurité du développement (DevSecOps)', description: 'Intégration de la sécurité dans le développement logiciel', objective: 'Produire des logiciels sécurisés par conception', maturityCriteria: { 1: ['Sécurité non intégrée'], 2: ['Tests ponctuels en fin de développement'], 3: ['SAST/DAST dans le pipeline CI/CD'], 4: ['DevSecOps mature, shift-left'], 5: ['Security as Code, déploiement zero-trust'] }, regulatoryMappings: { iso27001: ['8.25', '8.26', '8.27', '8.28'], dora: ['Art. 10'] } },
  { id: 'P4.O.015', pillarId: 'P4', name: 'Gestion des comptes privilégiés (PAM)', description: 'Contrôle renforcé des comptes à privilèges élevés', objective: 'Minimiser les risques liés aux comptes administrateurs', maturityCriteria: { 1: ['Partage de mots de passe admin'], 2: ['Inventaire des comptes privilégiés'], 3: ['PAM déployée, rotation des mots de passe'], 4: ['Session recording, just-in-time access'], 5: ['Accès privilégié zéro permanent'] }, regulatoryMappings: { iso27001: ['5.18', '8.2'], nis2: ['Art. 21(2)(b)'] } },
  { id: 'P4.O.016', pillarId: 'P4', name: 'Sécurité WiFi et accès distants', description: 'Sécurisation des connexions sans fil et à distance', objective: 'Protéger les accès distants et mobiles', maturityCriteria: { 1: ['WiFi ouvert, VPN non sécurisé'], 2: ['WPA2, VPN basique'], 3: ['WiFi entreprise sécurisé, VPN MFA'], 4: ['ZTNA, accès conditionnel'], 5: ['Zero Trust Access, SASE'] }, regulatoryMappings: { iso27001: ['8.20', '8.21'], nis2: ['Art. 21(2)(d)'] } },
  { id: 'P4.O.017', pillarId: 'P4', name: 'Sécurité des API', description: 'Protection des interfaces de programmation et services web', objective: 'Sécuriser tous les échanges via API', maturityCriteria: { 1: ['APIs non documentées, non sécurisées'], 2: ['Authentification basique sur APIs critiques'], 3: ['API Gateway, OAuth 2.0/OIDC, rate limiting'], 4: ['WAAP, validation des payloads'], 5: ['API security posture management, zero-trust API'] }, regulatoryMappings: { iso27001: ['8.23'], dora: ['Art. 9'] } },
  { id: 'P4.O.018', pillarId: 'P4', name: 'Gestion des médias amovibles', description: 'Contrôle de l\'utilisation des médias amovibles', objective: 'Prévenir les risques liés aux clés USB et supports amovibles', maturityCriteria: { 1: ['Usage libre des médias amovibles'], 2: ['Politique non appliquée'], 3: ['Contrôle technique DLP, chiffrement obligatoire'], 4: ['Interdiction des médias non approuvés'], 5: ['Media management complet, audit automatisé'] }, regulatoryMappings: { iso27001: ['7.10', '8.10'] } },
  // ── P5 extra (RC.006 → RC.013) ───────────────────────
  { id: 'P5.RC.006', pillarId: 'P5', name: 'Redondance des systèmes critiques', description: 'Architecture haute disponibilité pour les systèmes essentiels', objective: 'Éliminer les points de défaillance uniques', maturityCriteria: { 1: ['Pas de redondance'], 2: ['Redondance partielle'], 3: ['HA sur systèmes critiques'], 4: ['Architecture active-active, multi-site'], 5: ['Résilience by design, zero SPOF'] }, regulatoryMappings: { nis2: ['Art. 21(2)(c)'], dora: ['Art. 11'] } },
  { id: 'P5.RC.007', pillarId: 'P5', name: 'Communication de crise', description: 'Plan de communication lors d\'un incident', objective: 'Maîtriser la communication pendant et après un incident', maturityCriteria: { 1: ['Pas de plan de communication'], 2: ['Communication réactive non coordonnée'], 3: ['Plan de communication formalisé'], 4: ['Porte-paroles désignés, messages préparés'], 5: ['Communication automatisée, gestion de l\'image'] }, regulatoryMappings: { nis2: ['Art. 23'], iso27001: ['5.26'] } },
  { id: 'P5.RC.008', pillarId: 'P5', name: 'Gestion des dépendances critiques', description: 'Identification et gestion des dépendances externes critiques', objective: 'Minimiser l\'impact des défaillances de dépendances', maturityCriteria: { 1: ['Dépendances non identifiées'], 2: ['Liste partielle de fournisseurs critiques'], 3: ['Cartographie complète, plans de secours'], 4: ['Monitoring temps réel, alternatives identifiées'], 5: ['Résilience de l\'écosystème, SLA contractualisés'] }, regulatoryMappings: { dora: ['Art. 28'], nis2: ['Art. 21(2)(d)'] } },
  { id: 'P5.RC.009', pillarId: 'P5', name: 'Retour d\'expérience post-incident', description: 'Analyse et capitalisation après les incidents', objective: 'Améliorer en continu la résilience grâce au RETEX', maturityCriteria: { 1: ['Pas de RETEX'], 2: ['Bilan informel post-incident'], 3: ['RETEX structuré, actions correctives'], 4: ['RETEX partagé, amélioration systémique'], 5: ['Learning organization, adaptation proactive'] }, regulatoryMappings: { iso27001: ['5.27', '10.2'], dora: ['Art. 17'] } },
  { id: 'P5.RC.010', pillarId: 'P5', name: 'Continuité des chaînes d\'approvisionnement', description: 'Résilience de la supply chain en cas d\'incident fournisseur', objective: 'Maintenir l\'activité malgré une défaillance fournisseur', maturityCriteria: { 1: ['Pas de plan fournisseur alternatif'], 2: ['Fournisseurs de secours identifiés'], 3: ['Stratégie multi-source formalisée'], 4: ['Exercices de basculement fournisseur'], 5: ['Résilience supply chain by design'] }, regulatoryMappings: { dora: ['Art. 28'], nis2: ['Art. 21(2)(d)'] } },
  { id: 'P5.RC.011', pillarId: 'P5', name: 'Assurance et risques résiduels', description: 'Couverture assurantielle adaptée au risque résiduel', objective: 'Transférer le risque résiduel via des mécanismes d\'assurance', maturityCriteria: { 1: ['Pas d\'assurance cyber'], 2: ['Assurance générale'], 3: ['Police cyber dédiée'], 4: ['Couverture optimisée, stress tests'], 5: ['Programme assurance intégré, paramétrique'] }, regulatoryMappings: { dora: ['Art. 6'] } },
  { id: 'P5.RC.012', pillarId: 'P5', name: 'Maintien en condition de sécurité (MCS)', description: 'Programme continu de maintien en condition opérationnelle et sécurisée', objective: 'Garantir le niveau de sécurité dans la durée', maturityCriteria: { 1: ['Pas de MCS formalisé'], 2: ['MCS réactif aux incidents'], 3: ['MCS planifié, patch management'], 4: ['MCS continu, automatisé'], 5: ['MCS prédictif, AI-driven'] }, regulatoryMappings: { nis2: ['Art. 21(2)(d)'], iso27001: ['10.2'] } },
  { id: 'P5.RC.013', pillarId: 'P5', name: 'Architecture Zero Trust', description: 'Transformation vers un modèle de sécurité Zero Trust', objective: 'Ne jamais faire confiance, toujours vérifier', maturityCriteria: { 1: ['Architecture périmétrique classique'], 2: ['Principes Zero Trust connus non implémentés'], 3: ['ZTNA pour accès distants, MFA universel'], 4: ['Micro-segmentation, inspection continue du trafic'], 5: ['Zero Trust complet toutes couches'] }, regulatoryMappings: { nis2: ['Art. 21(2)(b)'], dora: ['Art. 9'] } },
  // ── P6 extra (T.006 → T.014) ─────────────────────────
  { id: 'P6.T.006', pillarId: 'P6', name: 'Gestion des incidents fournisseurs', description: 'Procédures de réponse aux incidents impliquant des tiers', objective: 'Répondre efficacement aux incidents chez les prestataires', maturityCriteria: { 1: ['Pas de procédure incident tiers'], 2: ['Escalade informelle vers le fournisseur'], 3: ['Procédure formalisée, obligations de notification'], 4: ['Coordination de crise avec les tiers critiques'], 5: ['Playbooks conjoints, exercices inter-organisations'] }, regulatoryMappings: { dora: ['Art. 19'], iso27001: ['5.22'] } },
  { id: 'P6.T.007', pillarId: 'P6', name: 'Sécurité de la chaîne logicielle', description: 'Maîtrise des risques liés aux composants logiciels tiers', objective: 'Sécuriser les dépendances logicielles', maturityCriteria: { 1: ['Pas de gestion des dépendances'], 2: ['Inventaire partiel, mises à jour manuelles'], 3: ['SCA automatisé, SBOM produit'], 4: ['Politique open source, revue régulière'], 5: ['Supply chain security complète, attestations'] }, regulatoryMappings: { iso27001: ['8.19', '8.30'], dora: ['Art. 10'] } },
  { id: 'P6.T.008', pillarId: 'P6', name: 'Due diligence sécurité M&A', description: 'Évaluation de la posture de sécurité lors d\'acquisitions', objective: 'Intégrer la sécurité dans les processus de due diligence M&A', maturityCriteria: { 1: ['Sécurité non évaluée en M&A'], 2: ['Revue superficielle'], 3: ['Due diligence structurée, rapport de risque'], 4: ['Évaluation approfondie, plan d\'intégration'], 5: ['CGEF assessment systématique, note d\'investisseur'] }, regulatoryMappings: { iso27001: ['5.19'] } },
  { id: 'P6.T.009', pillarId: 'P6', name: 'Offboarding des tiers', description: 'Procédures de décommissionnement sécurisé des accès tiers', objective: 'Garantir la révocation des accès à la fin du contrat', maturityCriteria: { 1: ['Pas de procédure d\'offboarding'], 2: ['Révocation manuelle et tardive'], 3: ['Procédure formalisée, checklist offboarding'], 4: ['Offboarding automatisé, vérification des accès résiduels'], 5: ['Processus certifié, audit de sortie systématique'] }, regulatoryMappings: { iso27001: ['5.11', '6.5'] } },
  { id: 'P6.T.010', pillarId: 'P6', name: 'Gestion des accès tiers', description: 'Contrôle des accès accordés aux prestataires', objective: 'Limiter et tracer les accès tiers aux systèmes sensibles', maturityCriteria: { 1: ['Accès tiers non contrôlés'], 2: ['Accès sans processus formel'], 3: ['Just-in-time access, VPN dédié'], 4: ['PAM pour tiers, session recording'], 5: ['Zero trust tiers, accès granulaire automatisé'] }, regulatoryMappings: { iso27001: ['5.18', '8.2'], dora: ['Art. 28'] } },
  { id: 'P6.T.011', pillarId: 'P6', name: 'Transfert de données vers les tiers', description: 'Encadrement des échanges de données sensibles avec les prestataires', objective: 'Sécuriser et tracer tous les transferts de données', maturityCriteria: { 1: ['Transferts non contrôlés'], 2: ['Transferts par email basique'], 3: ['Protocoles sécurisés, chiffrement obligatoire'], 4: ['DLP sur transferts, journalisation'], 5: ['Data room sécurisée, audit trail'] }, regulatoryMappings: { iso27001: ['5.14'], rgpd: ['Art. 28', 'Art. 44'] } },
  { id: 'P6.T.012', pillarId: 'P6', name: 'Concentration des risques fournisseurs', description: 'Gestion du risque de concentration sur un fournisseur critique', objective: 'Réduire la dépendance excessive envers un prestataire unique', maturityCriteria: { 1: ['Dépendance non identifiée'], 2: ['Fournisseurs critiques identifiés'], 3: ['Politique de diversification'], 4: ['Plan de sortie pour chaque tiers critique'], 5: ['Multi-sourcing systématique, exit plans testés'] }, regulatoryMappings: { dora: ['Art. 28', 'Art. 31'] } },
  { id: 'P6.T.013', pillarId: 'P6', name: 'Standards imposés aux tiers', description: 'Exigences de certification et standards imposés aux fournisseurs', objective: 'Élever le niveau de sécurité de l\'écosystème', maturityCriteria: { 1: ['Pas d\'exigences de certification'], 2: ['Préférence pour les fournisseurs certifiés'], 3: ['Certification ISO 27001 exigée pour tiers critiques'], 4: ['Programme de labellisation fournisseurs'], 5: ['Écosystème certifié, contribution à la maturité sectorielle'] }, regulatoryMappings: { nis2: ['Art. 21(2)(d)'], dora: ['Art. 28'] } },
  { id: 'P6.T.014', pillarId: 'P6', name: 'Rapport de conformité fournisseurs', description: 'Reporting régulier sur la conformité et la maturité des tiers', objective: 'Maintenir une vision consolidée de la posture de sécurité des tiers', maturityCriteria: { 1: ['Pas de reporting tiers'], 2: ['Synthèse annuelle informelle'], 3: ['Tableau de bord TPRM trimestriel'], 4: ['Reporting temps réel via plateforme TPRM'], 5: ['KRI tiers intégrés au pilotage stratégique'] }, regulatoryMappings: { dora: ['Art. 28'], iso27001: ['9.1'] } },
  // ── P7 extra (D.006 → D.015) ─────────────────────────
  { id: 'P7.D.006', pillarId: 'P7', name: 'Délégué à la Protection des Données (DPO)', description: 'Désignation et missions du DPO', objective: 'Assurer la fonction DPO conformément au RGPD', maturityCriteria: { 1: ['Pas de DPO'], 2: ['DPO désigné sans ressources'], 3: ['DPO opérationnel, missions définies'], 4: ['DPO intégré à la gouvernance, indépendant'], 5: ['DPO stratégique, référence sectorielle'] }, regulatoryMappings: { rgpd: ['Art. 37', 'Art. 38', 'Art. 39'] } },
  { id: 'P7.D.007', pillarId: 'P7', name: 'Registre des traitements', description: 'Tenue du registre des activités de traitement', objective: 'Disposer d\'un registre complet et à jour', maturityCriteria: { 1: ['Pas de registre'], 2: ['Registre partiel'], 3: ['Registre complet et mis à jour'], 4: ['Registre dynamique, lié aux systèmes'], 5: ['Registre automatisé, validé par audit'] }, regulatoryMappings: { rgpd: ['Art. 30'] } },
  { id: 'P7.D.008', pillarId: 'P7', name: 'Analyse d\'impact (PIA/DPIA)', description: 'Réalisation des analyses d\'impact sur la protection des données', objective: 'Évaluer et réduire les risques pour la vie privée', maturityCriteria: { 1: ['Pas de PIA réalisé'], 2: ['PIA ponctuel sur demande CNIL'], 3: ['PIA systématique sur traitements à risque'], 4: ['PIA intégré aux projets'], 5: ['PIA automatisé, privacy by design systémique'] }, regulatoryMappings: { rgpd: ['Art. 35'] } },
  { id: 'P7.D.009', pillarId: 'P7', name: 'Gestion des consentements', description: 'Collecte et gestion des consentements des personnes', objective: 'Obtenir et maintenir des consentements valides', maturityCriteria: { 1: ['Pas de gestion des consentements'], 2: ['Cases à cocher basiques'], 3: ['CMP conforme, registre des consentements'], 4: ['Gestion granulaire, audit complet'], 5: ['Consentement continu, transparence totale'] }, regulatoryMappings: { rgpd: ['Art. 6', 'Art. 7', 'Art. 13', 'Art. 14'] } },
  { id: 'P7.D.010', pillarId: 'P7', name: 'Sécurité des bases de données', description: 'Protection des bases de données contenant des données personnelles', objective: 'Sécuriser les bases de données contre les accès non autorisés', maturityCriteria: { 1: ['Bases de données non sécurisées'], 2: ['Contrôle d\'accès basique'], 3: ['Chiffrement, audit des accès DB'], 4: ['DAM (Database Activity Monitoring)'], 5: ['Zero trust DB, masquage, tokenisation'] }, regulatoryMappings: { rgpd: ['Art. 32'], iso27001: ['8.24'] } },
  { id: 'P7.D.011', pillarId: 'P7', name: 'Minimisation des données', description: 'Application du principe de minimisation des données collectées', objective: 'Ne collecter que les données strictement nécessaires', maturityCriteria: { 1: ['Collecte excessive non contrôlée'], 2: ['Sensibilisation à la minimisation'], 3: ['Revue des données collectées'], 4: ['Privacy by design systématique'], 5: ['Data lifecycle management automatisé'] }, regulatoryMappings: { rgpd: ['Art. 5(1)(c)', 'Art. 25'] } },
  { id: 'P7.D.012', pillarId: 'P7', name: 'Rétention et suppression des données', description: 'Politique de durée de conservation et suppression des données', objective: 'Respecter les durées légales de conservation', maturityCriteria: { 1: ['Pas de politique de rétention'], 2: ['Durées indicatives non appliquées'], 3: ['Politique formalisée, processus de suppression'], 4: ['Suppression automatisée, preuve de destruction'], 5: ['Data lifecycle complet, conformité démontrée'] }, regulatoryMappings: { rgpd: ['Art. 5(1)(e)', 'Art. 17'] } },
  { id: 'P7.D.013', pillarId: 'P7', name: 'Pseudonymisation et anonymisation', description: 'Techniques de protection des données pour l\'usage analytique', objective: 'Réduire l\'exposition des données personnelles', maturityCriteria: { 1: ['Pas de pseudonymisation'], 2: ['Pseudonymisation basique ad-hoc'], 3: ['Standard de pseudonymisation défini'], 4: ['Pseudonymisation systématique dans les analyses'], 5: ['Anonymisation prouvée, Privacy Enhancing Technologies'] }, regulatoryMappings: { rgpd: ['Art. 4(5)', 'Art. 25', 'Art. 89'] } },
  { id: 'P7.D.014', pillarId: 'P7', name: 'Sécurité des données en mobilité', description: 'Protection des données sur les appareils mobiles', objective: 'Sécuriser les données accédées depuis des appareils mobiles', maturityCriteria: { 1: ['Pas de politique mobile'], 2: ['MDM basique'], 3: ['MDM complet, chiffrement obligatoire'], 4: ['MAM, conteneurisation des données pro'], 5: ['Zero trust mobile, BYOD sécurisé complet'] }, regulatoryMappings: { rgpd: ['Art. 32'], iso27001: ['6.7'] } },
  { id: 'P7.D.015', pillarId: 'P7', name: 'Gouvernance de la donnée', description: 'Programme global de gouvernance des données', objective: 'Assurer la qualité, la fiabilité et la sécurité des données', maturityCriteria: { 1: ['Pas de gouvernance des données'], 2: ['Data owners identifiés pour certains domaines'], 3: ['Data governance framework défini'], 4: ['Data catalog, data lineage'], 5: ['Data mesh, gouvernance distribuée mature'] }, regulatoryMappings: { rgpd: ['Art. 5', 'Art. 24'], iso27001: ['5.9'] } },
  // ── P8 extra (I.006 → I.015) ─────────────────────────
  { id: 'P8.I.006', pillarId: 'P8', name: 'Automatisation de la sécurité (SOAR)', description: 'Automatisation des processus de sécurité et de réponse aux incidents', objective: 'Réduire le temps de réponse grâce à l\'automatisation', maturityCriteria: { 1: ['Pas d\'automatisation'], 2: ['Scripts basiques'], 3: ['Playbooks SOAR pour incidents courants'], 4: ['SOAR intégré, orchestration multi-outils'], 5: ['Réponse autonome, auto-healing généralisé'] }, regulatoryMappings: { nis2: ['Art. 21(2)(b)'], dora: ['Art. 10'] } },
  { id: 'P8.I.007', pillarId: 'P8', name: 'Sécurité des projets de transformation', description: 'Intégration de la sécurité dans les projets de transformation digitale', objective: 'Garantir que les transformations n\'augmentent pas le risque', maturityCriteria: { 1: ['Sécurité ignorée dans les transformations'], 2: ['Revue de sécurité en fin de projet'], 3: ['Security gate systématique dans les projets'], 4: ['Security champion dans chaque équipe projet'], 5: ['Transformation sécurisée by design'] }, regulatoryMappings: { iso27001: ['6.1.2', '8.25'] } },
  { id: 'P8.I.008', pillarId: 'P8', name: 'Gouvernance cyber quantique', description: 'Préparation aux risques cryptographiques liés à l\'informatique quantique', objective: 'Anticiper l\'obsolescence des algorithmes cryptographiques actuels', maturityCriteria: { 1: ['Pas de prise en compte'], 2: ['Sensibilisation aux risques quantiques'], 3: ['Inventaire des systèmes cryptographiques'], 4: ['Plan de migration post-quantique'], 5: ['Migration PQC en cours, crypto-agilité'] }, regulatoryMappings: { iso27001: ['8.24'] } },
  { id: 'P8.I.009', pillarId: 'P8', name: 'Partage d\'information sectoriel (ISAC)', description: 'Participation aux cercles de partage d\'information sur les menaces', objective: 'Contribuer et bénéficier du partage d\'intelligence sectoriel', maturityCriteria: { 1: ['Pas de participation'], 2: ['Lecture des publications ISAC'], 3: ['Adhésion formelle, contribution basique'], 4: ['Contribution active, partage de CTI'], 5: ['Leadership sectoriel, co-pilotage de l\'ISAC'] }, regulatoryMappings: { nis2: ['Art. 26'], dora: ['Art. 13'] } },
  { id: 'P8.I.010', pillarId: 'P8', name: 'Innovation et R&D sécurité', description: 'Programme d\'innovation et de recherche appliquée en sécurité', objective: 'Maintenir une avance technologique en cybersécurité', maturityCriteria: { 1: ['Pas d\'investissement R&D'], 2: ['Projets de veille ponctuels'], 3: ['Programme R&D structuré, PoC réguliers'], 4: ['Partenariats académiques, dépôts de brevets'], 5: ['Innovation ouverte, contributions majeures à l\'écosystème'] }, regulatoryMappings: { iso27001: ['5.7'] } },
  { id: 'P8.I.011', pillarId: 'P8', name: 'Sécurité des environnements DevOps', description: 'Sécurisation des pipelines CI/CD et environnements de développement', objective: 'Protéger les environnements de développement et de déploiement', maturityCriteria: { 1: ['CI/CD non sécurisé'], 2: ['Scans basiques dans le pipeline'], 3: ['Pipeline sécurisé, secrets management'], 4: ['Signed artifacts, SBOM, attestations'], 5: ['Supply chain security complète, SLSA niveau 4'] }, regulatoryMappings: { iso27001: ['8.25', '8.27', '8.28'], dora: ['Art. 10'] } },
  { id: 'P8.I.012', pillarId: 'P8', name: 'Sécurité des microservices', description: 'Sécurité spécifique aux architectures distribuées et conteneurisées', objective: 'Sécuriser les environnements conteneurisés et les microservices', maturityCriteria: { 1: ['Pas de considération spécifique conteneurs'], 2: ['Images vérifiées, accès basique'], 3: ['Security policies K8s, scanning des images'], 4: ['Service mesh mTLS, Pod Security Standards'], 5: ['Zero trust microservices, eBPF security'] }, regulatoryMappings: { iso27001: ['8.25', '8.27'], nis2: ['Art. 21(2)(d)'] } },
  { id: 'P8.I.013', pillarId: 'P8', name: 'Gestion de l\'identité numérique', description: 'Stratégie d\'identité numérique pour l\'ère zero trust', objective: 'Disposer d\'une architecture d\'identité moderne et sécurisée', maturityCriteria: { 1: ['Active Directory vieillissant'], 2: ['IAM moderne sur certains périmètres'], 3: ['IdP centralisé, fédération d\'identité'], 4: ['Passwordless, FIDO2'], 5: ['Decentralized Identity, Self-Sovereign Identity'] }, regulatoryMappings: { iso27001: ['5.15', '5.16'], dora: ['Art. 9'] } },
  { id: 'P8.I.014', pillarId: 'P8', name: 'Programme bug bounty', description: 'Mise en place d\'un programme de recherche de vulnérabilités', objective: 'Exploiter l\'intelligence collective pour améliorer la sécurité', maturityCriteria: { 1: ['Pas de programme de divulgation'], 2: ['Politique de divulgation coordonnée (CVD)'], 3: ['Programme bug bounty privé'], 4: ['Bug bounty public, périmètre étendu'], 5: ['Programme mature, récompenses compétitives'] }, regulatoryMappings: { nis2: ['Art. 12'] } },
  { id: 'P8.I.015', pillarId: 'P8', name: 'Sécurité des données massives (Big Data)', description: 'Protection des architectures de données massives', objective: 'Sécuriser les lacs de données et architectures analytiques', maturityCriteria: { 1: ['Data lake non sécurisé'], 2: ['Contrôle d\'accès basique'], 3: ['Data security posture management'], 4: ['Chiffrement, masquage, audit trail complet'], 5: ['Data security mesh, gouvernance automatisée'] }, regulatoryMappings: { rgpd: ['Art. 25', 'Art. 32'], iso27001: ['8.24'] } },
];

export const FRAMEWORKS: Framework[] = [
  { id: 'iso27001', name: 'ISO 27001:2022', version: '2022', controlsCount: 93, color: '#1565C0' },
  { id: 'nis2', name: 'NIS2', version: '2022', controlsCount: 21, color: '#2E7D32' },
  { id: 'dora', name: 'DORA', version: '2022', controlsCount: 30, color: '#F57C00' },
  { id: 'rgpd', name: 'RGPD', version: '2016', controlsCount: 99, color: '#7B1FA2' },
  { id: 'nist_csf', name: 'NIST CSF 2.0', version: '2024', controlsCount: 106, color: '#0288D1' },
  { id: 'cis_v8', name: 'CIS Controls v8.1', version: '2023', controlsCount: 153, color: '#455A64' },
  { id: 'soc2', name: 'SOC 2 Type II', version: '2022', controlsCount: 64, color: '#C62828' },
  { id: 'pci_dss', name: 'PCI-DSS v4.0', version: '2024', controlsCount: 281, color: '#00838F' },
];
export function getProcessesByPillar(pillarId: PillarId): Process[] {
  return PROCESSES.filter((p) => p.pillarId === pillarId);
}

export function getPillarById(pillarId: PillarId): Pillar | undefined {
  return PILLARS.find((p) => p.id === pillarId);
}

export function getProcessById(processId: string): Process | undefined {
  return PROCESSES.find((p) => p.id === processId);
}

export function getMaturityColor(level: number): string {
  const colors: Record<number, string> = {
    1: '#D32F2F',
    2: '#F57C00',
    3: '#FDD835',
    4: '#43A047',
    5: '#1565C0',
  };
  return colors[level] || '#94A3B8';
}

export function getMaturityLabel(level: number): string {
  const labels: Record<number, string> = {
    1: 'Initial',
    2: 'Reproductible',
    3: 'Defini',
    4: 'Gere',
    5: 'Optimise',
  };
  return labels[level] || 'Non evalue';
}
