import type { Pillar, Process, Framework, PillarId } from './types';

export const PILLARS: Pillar[] = [
  {
    id: 'P1',
    name: 'Gouvernance & Leadership',
    description: 'Pilotage strategique de la cybersecurite au niveau direction',
    processCount: 15,
    weight: 0.20,
  },
  {
    id: 'P2',
    name: 'Gestion des Risques Cyber',
    description: 'Identification, evaluation et traitement des risques',
    processCount: 16,
    weight: 0.18,
  },
  {
    id: 'P3',
    name: 'Conformite & Reglementation',
    description: 'Conformite aux exigences reglementaires et normatives',
    processCount: 14,
    weight: 0.12,
  },
  {
    id: 'P4',
    name: 'Securite Operationnelle',
    description: 'Mesures de securite techniques et operationnelles',
    processCount: 18,
    weight: 0.15,
  },
  {
    id: 'P5',
    name: 'Resilience & Continuite',
    description: 'Capacite de reprise et continuite des activites',
    processCount: 13,
    weight: 0.12,
  },
  {
    id: 'P6',
    name: 'Gestion des Tiers (TPRM)',
    description: 'Securite de la chaine de sous-traitance',
    processCount: 14,
    weight: 0.08,
  },
  {
    id: 'P7',
    name: 'Protection des Donnees',
    description: 'Protection et confidentialite des donnees',
    processCount: 15,
    weight: 0.07,
  },
  {
    id: 'P8',
    name: 'Innovation & Transformation',
    description: 'Integration de la securite dans la transformation digitale',
    processCount: 15,
    weight: 0.08,
  },
];

export const PROCESSES: Process[] = [
  {
    id: 'P1.G.001',
    pillarId: 'P1',
    name: 'Strategie cybersecurite',
    description: 'Definition et revision de la strategie cybersecurite alignee sur les objectifs metiers',
    objective: 'Disposer d\'une strategie cybersecurite formalisee et approuvee par la direction',
    maturityCriteria: {
      1: ['Pas de strategie formalisee'],
      2: ['Strategie informelle ou partielle'],
      3: ['Strategie documentee et communiquee'],
      4: ['Strategie revisee annuellement avec KPIs'],
      5: ['Strategie integree et pilotee en temps reel'],
    },
    regulatoryMappings: { iso27001: ['5.1', '5.2'], nis2: ['Art. 21(2)(a)'], dora: ['Art. 5'] },
  },
  {
    id: 'P1.G.002',
    pillarId: 'P1',
    name: 'Gouvernance et organisation',
    description: 'Structure organisationnelle de la fonction cybersecurite',
    objective: 'Disposer d\'une organisation claire avec des roles et responsabilites definis',
    maturityCriteria: {
      1: ['Aucune organisation formelle'],
      2: ['RSSI designe, perimetre flou'],
      3: ['Organisation documentee, RACI defini'],
      4: ['Comites reguliers, reporting direction'],
      5: ['Organisation agile, gouvernance integree'],
    },
    regulatoryMappings: { iso27001: ['5.3', '7.1'], nis2: ['Art. 21(2)(a)'] },
  },
  {
    id: 'P1.G.003',
    pillarId: 'P1',
    name: 'Budget et ressources',
    description: 'Allocation des ressources financieres et humaines',
    objective: 'Disposer de ressources adequates pour la cybersecurite',
    maturityCriteria: {
      1: ['Budget non identifie'],
      2: ['Budget ad-hoc sur projets'],
      3: ['Budget dedie annuel'],
      4: ['Budget pluriannuel avec ROI'],
      5: ['Budget optimise, benchmark sectoriel'],
    },
    regulatoryMappings: { iso27001: ['7.1'], nis2: ['Art. 21(2)(h)'] },
  },
  {
    id: 'P1.G.004',
    pillarId: 'P1',
    name: 'Politiques de securite',
    description: 'Corpus documentaire des politiques de securite',
    objective: 'Disposer de politiques couvrant tous les domaines de securite',
    maturityCriteria: {
      1: ['Aucune politique formalisee'],
      2: ['Politique generale uniquement'],
      3: ['Politiques thematiques completes'],
      4: ['Politiques revues, diffusees, controlees'],
      5: ['Politiques adaptatives, integrees aux processus'],
    },
    regulatoryMappings: { iso27001: ['5.1', 'A.5.1'], nis2: ['Art. 21(2)(a)'] },
  },
  {
    id: 'P1.G.005',
    pillarId: 'P1',
    name: 'Comite de pilotage cyber',
    description: 'Instance de gouvernance dediee a la cybersecurite',
    objective: 'Piloter la cybersecurite au niveau direction',
    maturityCriteria: {
      1: ['Aucun comite'],
      2: ['Reunions ad-hoc'],
      3: ['Comite trimestriel avec compte-rendu'],
      4: ['Comite mensuel, indicateurs suivis'],
      5: ['Comite integre aux instances strategiques'],
    },
    regulatoryMappings: { iso27001: ['5.1'], nis2: ['Art. 20'] },
  },
  {
    id: 'P2.R.001',
    pillarId: 'P2',
    name: 'Cartographie des actifs',
    description: 'Inventaire exhaustif des actifs informationnels et systemes',
    objective: 'Connaitre l\'ensemble des actifs a proteger',
    maturityCriteria: {
      1: ['Pas d\'inventaire'],
      2: ['Inventaire partiel ou obsolete'],
      3: ['Inventaire complet et maintenu'],
      4: ['Inventaire automatise avec valorisation'],
      5: ['CMDB temps reel, integree aux outils'],
    },
    regulatoryMappings: { iso27001: ['A.5.9'], nis2: ['Art. 21(2)(b)'], dora: ['Art. 8'] },
  },
  {
    id: 'P2.R.002',
    pillarId: 'P2',
    name: 'Analyse de risques',
    description: 'Methodologie d\'analyse et d\'evaluation des risques cyber',
    objective: 'Identifier et evaluer les risques de maniere systematique',
    maturityCriteria: {
      1: ['Aucune analyse formelle'],
      2: ['Analyses ponctuelles, non methodiques'],
      3: ['Methodologie definie (EBIOS RM, ISO 27005)'],
      4: ['Analyses periodiques, quantifiees'],
      5: ['Analyse continue, integree aux processus'],
    },
    regulatoryMappings: { iso27001: ['6.1', '8.2'], nis2: ['Art. 21(2)(b)'], dora: ['Art. 6'] },
  },
  {
    id: 'P2.R.003',
    pillarId: 'P2',
    name: 'Traitement des risques',
    description: 'Plans de traitement et suivi des risques identifies',
    objective: 'Traiter les risques selon l\'appetence definie',
    maturityCriteria: {
      1: ['Pas de traitement formalise'],
      2: ['Traitement reactif au cas par cas'],
      3: ['Plans de traitement documentes'],
      4: ['Suivi regulier, indicateurs d\'efficacite'],
      5: ['Optimisation continue, arbitrage dynamique'],
    },
    regulatoryMappings: { iso27001: ['6.1.3', '8.3'], nis2: ['Art. 21(2)(b)'] },
  },
  {
    id: 'P2.R.004',
    pillarId: 'P2',
    name: 'Veille en vulnerabilites',
    description: 'Surveillance des vulnerabilites affectant les systemes',
    objective: 'Anticiper les menaces par la veille',
    maturityCriteria: {
      1: ['Pas de veille structuree'],
      2: ['Veille manuelle occasionnelle'],
      3: ['Abonnements CERT, process defini'],
      4: ['Veille automatisee, correlation assets'],
      5: ['Threat intelligence integree'],
    },
    regulatoryMappings: { iso27001: ['A.5.7'], nis2: ['Art. 21(2)(e)'] },
  },
  {
    id: 'P2.R.005',
    pillarId: 'P2',
    name: 'Gestion des vulnerabilites',
    description: 'Processus de detection et remediation des vulnerabilites',
    objective: 'Maintenir un niveau de vulnerabilite acceptable',
    maturityCriteria: {
      1: ['Pas de scan de vulnerabilites'],
      2: ['Scans ponctuels'],
      3: ['Scans reguliers, process de patch'],
      4: ['SLA de remediation, mesure conformite'],
      5: ['Automatisation complete, zero-day process'],
    },
    regulatoryMappings: { iso27001: ['A.8.8'], nis2: ['Art. 21(2)(e)'], dora: ['Art. 10'] },
  },
  {
    id: 'P3.C.001',
    pillarId: 'P3',
    name: 'Veille reglementaire',
    description: 'Suivi des evolutions reglementaires applicables',
    objective: 'Anticiper les obligations reglementaires',
    maturityCriteria: {
      1: ['Pas de veille reglementaire'],
      2: ['Veille informelle'],
      3: ['Veille structuree, responsable identifie'],
      4: ['Analyse d\'impact systematique'],
      5: ['Veille automatisee, anticipation'],
    },
    regulatoryMappings: { iso27001: ['4.2'], nis2: ['Art. 21'], dora: ['Art. 4'] },
  },
  {
    id: 'P3.C.002',
    pillarId: 'P3',
    name: 'Conformite ISO 27001',
    description: 'Mise en conformite avec la norme ISO 27001:2022',
    objective: 'Atteindre et maintenir la certification ISO 27001',
    maturityCriteria: {
      1: ['Non engage'],
      2: ['Gap analysis realisee'],
      3: ['SMSI documente et operationnel'],
      4: ['Certifie, audits internes reguliers'],
      5: ['Amelioration continue demontree'],
    },
    regulatoryMappings: { iso27001: ['All'], nis2: ['Art. 21(2)(j)'] },
  },
  {
    id: 'P3.C.003',
    pillarId: 'P3',
    name: 'Conformite NIS2',
    description: 'Conformite a la directive europeenne NIS2',
    objective: 'Respecter les exigences NIS2 avant echeance',
    maturityCriteria: {
      1: ['Non evalue'],
      2: ['Perimetre identifie'],
      3: ['Plan de mise en conformite'],
      4: ['Mesures implementees'],
      5: ['Conformite totale, auditable'],
    },
    regulatoryMappings: { nis2: ['Art. 20-23'] },
  },
  {
    id: 'P3.C.004',
    pillarId: 'P3',
    name: 'Conformite DORA',
    description: 'Conformite au reglement DORA pour le secteur financier',
    objective: 'Respecter les exigences DORA',
    maturityCriteria: {
      1: ['Non applicable ou non evalue'],
      2: ['Gap analysis initiale'],
      3: ['Cadre de resilience documente'],
      4: ['Tests de resilience realises'],
      5: ['Conformite complete, reporting ACPR'],
    },
    regulatoryMappings: { dora: ['All'] },
  },
  {
    id: 'P3.C.005',
    pillarId: 'P3',
    name: 'Audit interne cyber',
    description: 'Programme d\'audits internes de securite',
    objective: 'Controler l\'application des mesures de securite',
    maturityCriteria: {
      1: ['Pas d\'audit interne'],
      2: ['Audits ponctuels'],
      3: ['Programme annuel d\'audits'],
      4: ['Suivi des non-conformites, KPIs'],
      5: ['Audit continu, assurance qualite'],
    },
    regulatoryMappings: { iso27001: ['9.2'], nis2: ['Art. 21(2)(j)'] },
  },
  {
    id: 'P4.O.001',
    pillarId: 'P4',
    name: 'Gestion des acces',
    description: 'Controle des acces logiques aux systemes',
    objective: 'Garantir que seuls les utilisateurs autorises accedent aux ressources',
    maturityCriteria: {
      1: ['Gestion basique des comptes'],
      2: ['Politique de mots de passe'],
      3: ['IAM centralise, RBAC'],
      4: ['MFA generalise, revues d\'acces'],
      5: ['Zero Trust, acces adaptatif'],
    },
    regulatoryMappings: { iso27001: ['A.5.15', 'A.5.16', 'A.5.18'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 9'] },
  },
  {
    id: 'P4.O.002',
    pillarId: 'P4',
    name: 'Securite reseau',
    description: 'Protection du reseau et segmentation',
    objective: 'Proteger l\'infrastructure reseau des menaces',
    maturityCriteria: {
      1: ['Reseau plat, firewall basique'],
      2: ['DMZ, regles firewall documentees'],
      3: ['Segmentation, IDS/IPS'],
      4: ['Micro-segmentation, NDR'],
      5: ['Software-defined security, automatisation'],
    },
    regulatoryMappings: { iso27001: ['A.8.20', 'A.8.21'], nis2: ['Art. 21(2)(c)'] },
  },
  {
    id: 'P4.O.003',
    pillarId: 'P4',
    name: 'Protection endpoint',
    description: 'Securisation des postes de travail et terminaux',
    objective: 'Proteger les endpoints contre les menaces',
    maturityCriteria: {
      1: ['Antivirus basique'],
      2: ['Antivirus centralise, mises a jour'],
      3: ['EDR deploye'],
      4: ['EDR avec reponse automatisee'],
      5: ['XDR integre, threat hunting'],
    },
    regulatoryMappings: { iso27001: ['A.8.1', 'A.8.7'], nis2: ['Art. 21(2)(c)'] },
  },
  {
    id: 'P4.O.004',
    pillarId: 'P4',
    name: 'Supervision de securite (SOC)',
    description: 'Surveillance et detection des incidents de securite',
    objective: 'Detecter les incidents de securite rapidement',
    maturityCriteria: {
      1: ['Pas de supervision centralisee'],
      2: ['Logs collectes, analyse manuelle'],
      3: ['SIEM operationnel, use cases'],
      4: ['SOC 24/7, SLA de detection'],
      5: ['SOC avance, SOAR, ML'],
    },
    regulatoryMappings: { iso27001: ['A.8.15', 'A.8.16'], nis2: ['Art. 21(2)(c)'], dora: ['Art. 10'] },
  },
  {
    id: 'P4.O.005',
    pillarId: 'P4',
    name: 'Gestion des incidents',
    description: 'Processus de reponse aux incidents de securite',
    objective: 'Repondre efficacement aux incidents',
    maturityCriteria: {
      1: ['Pas de processus formalise'],
      2: ['Procedure basique de reponse'],
      3: ['Processus documente, equipe identifiee'],
      4: ['Playbooks, exercices reguliers'],
      5: ['Automatisation SOAR, amelioration continue'],
    },
    regulatoryMappings: { iso27001: ['A.5.24', 'A.5.25', 'A.5.26'], nis2: ['Art. 21(2)(c)', 'Art. 23'], dora: ['Art. 17'] },
  },
  {
    id: 'P5.B.001',
    pillarId: 'P5',
    name: 'Plan de continuite (PCA)',
    description: 'Plan de continuite des activites metiers',
    objective: 'Assurer la continuite des activites critiques',
    maturityCriteria: {
      1: ['Pas de PCA'],
      2: ['PCA partiel ou obsolete'],
      3: ['PCA documente, BIA realise'],
      4: ['PCA teste annuellement'],
      5: ['PCA integre, resilience prouvee'],
    },
    regulatoryMappings: { iso27001: ['A.5.29', 'A.5.30'], nis2: ['Art. 21(2)(c)'], dora: ['Art. 11', 'Art. 12'] },
  },
  {
    id: 'P5.B.002',
    pillarId: 'P5',
    name: 'Plan de reprise (PRA)',
    description: 'Plan de reprise d\'activite apres sinistre',
    objective: 'Permettre la reprise des systemes critiques',
    maturityCriteria: {
      1: ['Pas de PRA'],
      2: ['Sauvegardes basiques'],
      3: ['PRA documente, RTO/RPO definis'],
      4: ['PRA teste, site de secours'],
      5: ['Reprise automatisee, exercices'],
    },
    regulatoryMappings: { iso27001: ['A.5.30'], nis2: ['Art. 21(2)(c)'], dora: ['Art. 12'] },
  },
  {
    id: 'P5.B.003',
    pillarId: 'P5',
    name: 'Sauvegardes',
    description: 'Politique et processus de sauvegarde des donnees',
    objective: 'Garantir la disponibilite des donnees',
    maturityCriteria: {
      1: ['Sauvegardes non systematiques'],
      2: ['Sauvegardes regulieres'],
      3: ['Politique 3-2-1, tests de restauration'],
      4: ['Sauvegardes immuables, chiffrees'],
      5: ['Sauvegarde continue, air-gap'],
    },
    regulatoryMappings: { iso27001: ['A.8.13'], nis2: ['Art. 21(2)(c)'], dora: ['Art. 12'] },
  },
  {
    id: 'P5.B.004',
    pillarId: 'P5',
    name: 'Gestion de crise cyber',
    description: 'Dispositif de gestion de crise en cas d\'incident majeur',
    objective: 'Gerer efficacement les crises cyber',
    maturityCriteria: {
      1: ['Pas de dispositif'],
      2: ['Contacts d\'urgence identifies'],
      3: ['Cellule de crise, procedures'],
      4: ['Exercices de crise annuels'],
      5: ['Cellule rodee, communication de crise'],
    },
    regulatoryMappings: { iso27001: ['A.5.24'], nis2: ['Art. 21(2)(c)'], dora: ['Art. 17'] },
  },
  {
    id: 'P5.B.005',
    pillarId: 'P5',
    name: 'Tests de resilience',
    description: 'Tests reguliers des capacites de resilience',
    objective: 'Valider l\'efficacite des plans de resilience',
    maturityCriteria: {
      1: ['Pas de tests'],
      2: ['Tests ponctuels'],
      3: ['Programme de tests annuel'],
      4: ['Tests realistes, retex formalise'],
      5: ['Tests continus, chaos engineering'],
    },
    regulatoryMappings: { iso27001: ['A.5.30'], dora: ['Art. 26', 'Art. 27'] },
  },
  {
    id: 'P6.T.001',
    pillarId: 'P6',
    name: 'Inventaire des tiers',
    description: 'Cartographie des fournisseurs et prestataires',
    objective: 'Connaitre l\'ensemble de la chaine de sous-traitance',
    maturityCriteria: {
      1: ['Pas d\'inventaire des tiers'],
      2: ['Liste partielle des fournisseurs'],
      3: ['Inventaire complet avec criticite'],
      4: ['Inventaire dynamique, dependances'],
      5: ['Chaine de valeur cartographiee'],
    },
    regulatoryMappings: { iso27001: ['A.5.19'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 28'] },
  },
  {
    id: 'P6.T.002',
    pillarId: 'P6',
    name: 'Due diligence securite',
    description: 'Evaluation de securite des tiers avant contractualisation',
    objective: 'S\'assurer de la maturite securite des tiers',
    maturityCriteria: {
      1: ['Pas d\'evaluation'],
      2: ['Questionnaire basique'],
      3: ['Due diligence formalisee'],
      4: ['Scoring securite, rating externe'],
      5: ['Evaluation continue, audit sur site'],
    },
    regulatoryMappings: { iso27001: ['A.5.20'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 28'] },
  },
  {
    id: 'P6.T.003',
    pillarId: 'P6',
    name: 'Clauses contractuelles',
    description: 'Exigences de securite dans les contrats',
    objective: 'Imposer des obligations de securite aux tiers',
    maturityCriteria: {
      1: ['Pas de clauses specifiques'],
      2: ['Clauses generiques'],
      3: ['Clauses adaptees au risque'],
      4: ['SLA securite, penalites'],
      5: ['Clauses dynamiques, droit d\'audit'],
    },
    regulatoryMappings: { iso27001: ['A.5.20'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 30'] },
  },
  {
    id: 'P6.T.004',
    pillarId: 'P6',
    name: 'Surveillance des tiers',
    description: 'Suivi continu de la posture securite des tiers',
    objective: 'Maintenir la visibilite sur les risques tiers',
    maturityCriteria: {
      1: ['Pas de surveillance'],
      2: ['Revue annuelle manuelle'],
      3: ['Surveillance trimestrielle'],
      4: ['Monitoring continu, alertes'],
      5: ['Integration SOC, threat intelligence'],
    },
    regulatoryMappings: { iso27001: ['A.5.22'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 28'] },
  },
  {
    id: 'P6.T.005',
    pillarId: 'P6',
    name: 'Gestion des incidents tiers',
    description: 'Processus de notification et gestion des incidents impliquant des tiers',
    objective: 'Reagir aux incidents de securite des tiers',
    maturityCriteria: {
      1: ['Pas de processus'],
      2: ['Notification contractuelle'],
      3: ['Processus de coordination'],
      4: ['Exercices conjoints'],
      5: ['Chaine d\'incident integree'],
    },
    regulatoryMappings: { iso27001: ['A.5.21'], nis2: ['Art. 21(2)(d)'] },
  },
  {
    id: 'P7.D.001',
    pillarId: 'P7',
    name: 'Classification des donnees',
    description: 'Schema de classification et marquage des donnees',
    objective: 'Identifier et proteger les donnees selon leur sensibilite',
    maturityCriteria: {
      1: ['Pas de classification'],
      2: ['Classification informelle'],
      3: ['Schema formalise, marquage'],
      4: ['Classification automatisee'],
      5: ['DLP integre, gouvernance data'],
    },
    regulatoryMappings: { iso27001: ['A.5.12', 'A.5.13'], rgpd: ['Art. 5'], nis2: ['Art. 21(2)(b)'] },
  },
  {
    id: 'P7.D.002',
    pillarId: 'P7',
    name: 'Chiffrement',
    description: 'Protection cryptographique des donnees sensibles',
    objective: 'Garantir la confidentialite des donnees',
    maturityCriteria: {
      1: ['Pas de chiffrement'],
      2: ['Chiffrement partiel'],
      3: ['Chiffrement at-rest et in-transit'],
      4: ['Gestion des cles centralisee'],
      5: ['Chiffrement de bout en bout, HSM'],
    },
    regulatoryMappings: { iso27001: ['A.8.24'], rgpd: ['Art. 32'], dora: ['Art. 9'] },
  },
  {
    id: 'P7.D.003',
    pillarId: 'P7',
    name: 'Conformite RGPD',
    description: 'Mise en conformite avec le RGPD',
    objective: 'Respecter les obligations du RGPD',
    maturityCriteria: {
      1: ['Non conforme'],
      2: ['Registre des traitements initie'],
      3: ['DPO, procedures, PIA'],
      4: ['Privacy by design, audits'],
      5: ['Conformite demontree, culture privacy'],
    },
    regulatoryMappings: { rgpd: ['All'] },
  },
  {
    id: 'P7.D.004',
    pillarId: 'P7',
    name: 'Gestion des droits',
    description: 'Processus de gestion des droits des personnes concernees',
    objective: 'Permettre l\'exercice des droits RGPD',
    maturityCriteria: {
      1: ['Pas de processus'],
      2: ['Traitement manuel au cas par cas'],
      3: ['Procedures documentees'],
      4: ['Portail self-service'],
      5: ['Automatisation, tracabilite complete'],
    },
    regulatoryMappings: { rgpd: ['Art. 15-22'] },
  },
  {
    id: 'P7.D.005',
    pillarId: 'P7',
    name: 'Notification de violation',
    description: 'Processus de notification des violations de donnees',
    objective: 'Respecter les delais de notification RGPD',
    maturityCriteria: {
      1: ['Pas de processus'],
      2: ['Procedure basique'],
      3: ['Processus 72h documente'],
      4: ['Exercices de notification'],
      5: ['Detection automatisee, reporting'],
    },
    regulatoryMappings: { rgpd: ['Art. 33', 'Art. 34'], nis2: ['Art. 23'] },
  },
  {
    id: 'P8.I.001',
    pillarId: 'P8',
    name: 'Security by Design',
    description: 'Integration de la securite des la conception des projets',
    objective: 'Integrer la securite dans le cycle de developpement',
    maturityCriteria: {
      1: ['Securite en fin de projet'],
      2: ['Revues securite ponctuelles'],
      3: ['Security champions, guidelines'],
      4: ['DevSecOps, shift-left'],
      5: ['Securite native, automatisee'],
    },
    regulatoryMappings: { iso27001: ['A.8.25'], rgpd: ['Art. 25'] },
  },
  {
    id: 'P8.I.002',
    pillarId: 'P8',
    name: 'Securite Cloud',
    description: 'Gouvernance de la securite des environnements cloud',
    objective: 'Maitriser les risques lies au cloud',
    maturityCriteria: {
      1: ['Shadow IT, cloud non gouverne'],
      2: ['Politique cloud basique'],
      3: ['CASB, gouvernance multi-cloud'],
      4: ['CSPM, conformite automatisee'],
      5: ['Cloud security maturity complete'],
    },
    regulatoryMappings: { iso27001: ['A.5.23'], nis2: ['Art. 21(2)(d)'], dora: ['Art. 28'] },
  },
  {
    id: 'P8.I.003',
    pillarId: 'P8',
    name: 'Securite applicative',
    description: 'Securisation du developpement logiciel',
    objective: 'Produire des applications securisees',
    maturityCriteria: {
      1: ['Pas de pratiques SSDLC'],
      2: ['Tests de securite ponctuels'],
      3: ['SAST/DAST integres'],
      4: ['Pipeline securise, SBOM'],
      5: ['DevSecOps mature, SCA continu'],
    },
    regulatoryMappings: { iso27001: ['A.8.25', 'A.8.26', 'A.8.27'], dora: ['Art. 10'] },
  },
  {
    id: 'P8.I.004',
    pillarId: 'P8',
    name: 'Securite IA/ML',
    description: 'Gouvernance de la securite des systemes d\'IA',
    objective: 'Maitriser les risques lies a l\'IA',
    maturityCriteria: {
      1: ['Pas de gouvernance IA'],
      2: ['Sensibilisation aux risques'],
      3: ['Politique IA, inventaire modeles'],
      4: ['Tests adversariaux, monitoring'],
      5: ['AI security mature, conformite AI Act'],
    },
    regulatoryMappings: {},
  },
  {
    id: 'P8.I.005',
    pillarId: 'P8',
    name: 'Veille technologique',
    description: 'Suivi des tendances et menaces emergentes',
    objective: 'Anticiper les evolutions technologiques',
    maturityCriteria: {
      1: ['Pas de veille structuree'],
      2: ['Veille informelle'],
      3: ['Veille organisee, partage interne'],
      4: ['R&D securite, POC reguliers'],
      5: ['Innovation securite, contributions'],
    },
    regulatoryMappings: { iso27001: ['A.5.7'] },
  },
];

export const FRAMEWORKS: Framework[] = [
  { id: 'iso27001', name: 'ISO 27001:2022', version: '2022', controlsCount: 93, color: '#1565C0' },
  { id: 'nis2', name: 'NIS2', version: '2022', controlsCount: 21, color: '#2E7D32' },
  { id: 'dora', name: 'DORA', version: '2022', controlsCount: 30, color: '#F57C00' },
  { id: 'rgpd', name: 'RGPD', version: '2016', controlsCount: 99, color: '#7B1FA2' },
  { id: 'nist_csf', name: 'NIST CSF 2.0', version: '2024', controlsCount: 106, color: '#0288D1' },
  { id: 'cis_v8', name: 'CIS Controls v8.1', version: '2023', controlsCount: 153, color: '#455A64' },
];

export function getProcessesByPillar(pillarId: PillarId): Process[] {
  return PROCESSES.filter((p) => p.pillarId === pillarId);
}

export function getPillarById(pillarId: PillarId): Pillar | undefined {
  return PILLARS.find((p) => p.id === pillarId);
}

export function getProcessById(processId: string): Process | undefined {
  return PROCESSES.find((p) => p.id === processId);
}

export function getMaturityColor(level: number): string {
  const colors: Record<number, string> = {
    1: '#D32F2F',
    2: '#F57C00',
    3: '#FDD835',
    4: '#43A047',
    5: '#1565C0',
  };
  return colors[level] || '#94A3B8';
}

export function getMaturityLabel(level: number): string {
  const labels: Record<number, string> = {
    1: 'Initial',
    2: 'Reproductible',
    3: 'Defini',
    4: 'Gere',
    5: 'Optimise',
  };
  return labels[level] || 'Non evalue';
}
