// Comprehensive mock data for CGEF Platform demo

export const mockOrganizations = [
  {
    id: 'org-1',
    name: 'Nexus Finance Group',
    sector: 'Finance',
    country: 'France',
    size: 'Enterprise',
    logo: null,
    cyberScore: 68,
    riskLevel: 'Medium',
    consultant: 'Sophie Laurent',
    lastActivity: '2026-05-08',
    frameworks: ['ISO 27001', 'NIS2', 'DORA', 'RGPD'],
    status: 'Active',
  },
  {
    id: 'org-2',
    name: 'MedCore Health Systems',
    sector: 'Healthcare',
    country: 'France',
    size: 'Mid-market',
    logo: null,
    cyberScore: 52,
    riskLevel: 'High',
    consultant: 'Marc Dupont',
    lastActivity: '2026-05-06',
    frameworks: ['ISO 27001', 'RGPD', 'NIS2'],
    status: 'Active',
  },
  {
    id: 'org-3',
    name: 'Industria Manufacturing',
    sector: 'Industry',
    country: 'France',
    size: 'Mid-market',
    logo: null,
    cyberScore: 74,
    riskLevel: 'Low',
    consultant: 'Claire Morin',
    lastActivity: '2026-05-07',
    frameworks: ['ISO 27001', 'NIS2', 'CIS Controls'],
    status: 'Active',
  },
];

export const mockUsers = [
  { id: 'u-1', name: 'Alexandre Dubois', email: 'a.dubois@nexusfinance.fr', role: 'ciso', org: 'org-1', avatar: null },
  { id: 'u-2', name: 'Sophie Laurent', email: 's.laurent@cgef-consult.fr', role: 'consultant', org: 'org-1', avatar: null },
  { id: 'u-3', name: 'Marc Dupont', email: 'm.dupont@cgef-consult.fr', role: 'consultant', org: 'org-2', avatar: null },
  { id: 'u-4', name: 'Claire Morin', email: 'c.morin@cgef-consult.fr', role: 'manager', org: 'org-3', avatar: null },
  { id: 'u-5', name: 'Thomas Bernard', email: 't.bernard@nexusfinance.fr', role: 'analyst', org: 'org-1', avatar: null },
  { id: 'u-6', name: 'Isabelle Petit', email: 'i.petit@medcore.fr', role: 'ciso', org: 'org-2', avatar: null },
  { id: 'u-7', name: 'Laurent Garnier', email: 'l.garnier@industria.fr', role: 'manager', org: 'org-3', avatar: null },
  { id: 'u-8', name: 'Camille Rousseau', email: 'c.rousseau@nexusfinance.fr', role: 'auditor', org: 'org-1', avatar: null },
  { id: 'u-9', name: 'Nicolas Martin', email: 'n.martin@cgef-consult.fr', role: 'admin', org: 'org-1', avatar: null },
  { id: 'u-10', name: 'Mathilde Simon', email: 'm.simon@medcore.fr', role: 'analyst', org: 'org-2', avatar: null },
];

export type RiskSeverity = 'critical' | 'high' | 'medium' | 'low';
export type RiskStatus = 'open' | 'mitigating' | 'accepted' | 'closed';
export type RiskTreatment = 'mitigate' | 'accept' | 'transfer' | 'avoid';

export const mockRisks = [
  {
    id: 'R-001',
    title: 'Ransomware attack on core banking systems',
    description: 'Threat of ransomware deployment targeting core banking infrastructure via phishing or supply chain compromise.',
    category: 'Cyber Threat',
    domain: 'Security Operations',
    owner: 'Alexandre Dubois',
    asset: 'Core Banking Platform',
    likelihood: 4,
    impact: 5,
    inherentScore: 20,
    residualScore: 12,
    severity: 'critical' as RiskSeverity,
    status: 'mitigating' as RiskStatus,
    treatment: 'mitigate' as RiskTreatment,
    dueDate: '2026-06-30',
    controls: ['C-014', 'C-022', 'C-037'],
    lastReviewed: '2026-04-15',
    trend: 'stable',
  },
  {
    id: 'R-002',
    title: 'Data breach via third-party vendor access',
    description: 'Unauthorized access to sensitive customer data through a compromised third-party vendor with elevated privileges.',
    category: 'Third-Party Risk',
    domain: 'Third Party Risk',
    owner: 'Thomas Bernard',
    asset: 'Customer Data Warehouse',
    likelihood: 3,
    impact: 5,
    inherentScore: 15,
    residualScore: 9,
    severity: 'critical' as RiskSeverity,
    status: 'mitigating' as RiskStatus,
    treatment: 'mitigate' as RiskTreatment,
    dueDate: '2026-05-31',
    controls: ['C-008', 'C-041'],
    lastReviewed: '2026-04-20',
    trend: 'increasing',
  },
  {
    id: 'R-003',
    title: 'DORA compliance gap - ICT incident reporting',
    description: 'Current incident classification and reporting procedures do not fully align with DORA Article 19 requirements for major ICT-related incidents.',
    category: 'Regulatory',
    domain: 'Compliance',
    owner: 'Alexandre Dubois',
    asset: 'Compliance Program',
    likelihood: 4,
    impact: 4,
    inherentScore: 16,
    residualScore: 10,
    severity: 'high' as RiskSeverity,
    status: 'open' as RiskStatus,
    treatment: 'mitigate' as RiskTreatment,
    dueDate: '2026-07-01',
    controls: ['C-055'],
    lastReviewed: '2026-05-01',
    trend: 'increasing',
  },
  {
    id: 'R-004',
    title: 'Privileged account compromise',
    description: 'Elevated risk of privileged credentials being stolen or misused, particularly service accounts with broad database access.',
    category: 'Identity & Access',
    domain: 'Identity & Access',
    owner: 'Thomas Bernard',
    asset: 'Active Directory / IAM',
    likelihood: 3,
    impact: 4,
    inherentScore: 12,
    residualScore: 8,
    severity: 'high' as RiskSeverity,
    status: 'mitigating' as RiskStatus,
    treatment: 'mitigate' as RiskTreatment,
    dueDate: '2026-06-15',
    controls: ['C-011', 'C-012'],
    lastReviewed: '2026-04-28',
    trend: 'decreasing',
  },
  {
    id: 'R-005',
    title: 'Cloud misconfiguration leading to data exposure',
    description: 'Inadequate cloud security posture management increases risk of inadvertent public exposure of sensitive datasets.',
    category: 'Cloud Security',
    domain: 'Cloud Security',
    owner: 'Sophie Laurent',
    asset: 'Azure Cloud Infrastructure',
    likelihood: 3,
    impact: 4,
    inherentScore: 12,
    residualScore: 6,
    severity: 'high' as RiskSeverity,
    status: 'mitigating' as RiskStatus,
    treatment: 'mitigate' as RiskTreatment,
    dueDate: '2026-06-30',
    controls: ['C-061', 'C-062'],
    lastReviewed: '2026-05-02',
    trend: 'decreasing',
  },
  {
    id: 'R-006',
    title: 'Inadequate business continuity for payment processing',
    description: 'RTO/RPO targets for payment processing systems exceed regulatory thresholds under DORA operational resilience requirements.',
    category: 'Business Continuity',
    domain: 'Business Continuity',
    owner: 'Alexandre Dubois',
    asset: 'Payment Processing Systems',
    likelihood: 2,
    impact: 5,
    inherentScore: 10,
    residualScore: 7,
    severity: 'high' as RiskSeverity,
    status: 'open' as RiskStatus,
    treatment: 'mitigate' as RiskTreatment,
    dueDate: '2026-09-30',
    controls: ['C-071', 'C-072'],
    lastReviewed: '2026-04-10',
    trend: 'stable',
  },
  {
    id: 'R-007',
    title: 'Insufficient security awareness training',
    description: 'Low completion rate of mandatory security awareness training increases susceptibility to social engineering attacks.',
    category: 'Human Risk',
    domain: 'Awareness & Training',
    owner: 'Camille Rousseau',
    asset: 'Workforce',
    likelihood: 4,
    impact: 3,
    inherentScore: 12,
    residualScore: 8,
    severity: 'medium' as RiskSeverity,
    status: 'mitigating' as RiskStatus,
    treatment: 'mitigate' as RiskTreatment,
    dueDate: '2026-06-01',
    controls: ['C-081'],
    lastReviewed: '2026-05-03',
    trend: 'decreasing',
  },
  {
    id: 'R-008',
    title: 'Legacy system patching gaps',
    description: 'Several legacy applications running unsupported software versions with known critical vulnerabilities.',
    category: 'Vulnerability Management',
    domain: 'Asset Management',
    owner: 'Thomas Bernard',
    asset: 'Legacy Applications',
    likelihood: 3,
    impact: 3,
    inherentScore: 9,
    residualScore: 6,
    severity: 'medium' as RiskSeverity,
    status: 'mitigating' as RiskStatus,
    treatment: 'mitigate' as RiskTreatment,
    dueDate: '2026-07-31',
    controls: ['C-023'],
    lastReviewed: '2026-04-25',
    trend: 'stable',
  },
  {
    id: 'R-009',
    title: 'GDPR data subject request processing delays',
    description: 'Current processes for handling data subject access requests (DSARs) may not consistently meet the 30-day response requirement.',
    category: 'Data Protection',
    domain: 'Data Protection',
    owner: 'Camille Rousseau',
    asset: 'GDPR Compliance Program',
    likelihood: 3,
    impact: 3,
    inherentScore: 9,
    residualScore: 5,
    severity: 'medium' as RiskSeverity,
    status: 'mitigating' as RiskStatus,
    treatment: 'mitigate' as RiskTreatment,
    dueDate: '2026-05-31',
    controls: ['C-091'],
    lastReviewed: '2026-05-04',
    trend: 'decreasing',
  },
  {
    id: 'R-010',
    title: 'Insider threat - privileged user monitoring gaps',
    description: 'Insufficient monitoring of privileged user activities across critical systems increases risk of data exfiltration by insiders.',
    category: 'Insider Threat',
    domain: 'Security Operations',
    owner: 'Alexandre Dubois',
    asset: 'SIEM / Monitoring Infrastructure',
    likelihood: 2,
    impact: 4,
    inherentScore: 8,
    residualScore: 5,
    severity: 'medium' as RiskSeverity,
    status: 'accepted' as RiskStatus,
    treatment: 'accept' as RiskTreatment,
    dueDate: '2026-12-31',
    controls: ['C-031'],
    lastReviewed: '2026-04-01',
    trend: 'stable',
  },
];

export type ComplianceStatus = 'compliant' | 'partial' | 'gap' | 'na';

export const mockComplianceFrameworks = [
  {
    id: 'iso27001',
    name: 'ISO 27001',
    version: '2022',
    totalControls: 93,
    compliant: 52,
    partial: 28,
    gap: 13,
    na: 0,
    percentage: 68,
    lastAudit: '2026-02-15',
    nextAudit: '2027-02-15',
    certificationStatus: 'In Progress',
    auditor: 'Bureau Veritas',
  },
  {
    id: 'nis2',
    name: 'NIS2',
    version: '2022/2555',
    totalControls: 46,
    compliant: 21,
    partial: 14,
    gap: 11,
    na: 0,
    percentage: 54,
    lastAudit: '2026-01-10',
    nextAudit: '2026-10-17',
    certificationStatus: 'Gap Analysis',
    auditor: 'Internal',
  },
  {
    id: 'dora',
    name: 'DORA',
    version: '2022/2554',
    totalControls: 35,
    compliant: 18,
    partial: 10,
    gap: 7,
    na: 0,
    percentage: 61,
    lastAudit: '2026-03-01',
    nextAudit: '2027-01-17',
    certificationStatus: 'Remediation',
    auditor: 'ACPR',
  },
  {
    id: 'rgpd',
    name: 'RGPD',
    version: '2016/679',
    totalControls: 28,
    compliant: 22,
    partial: 4,
    gap: 2,
    na: 0,
    percentage: 82,
    lastAudit: '2026-04-01',
    nextAudit: '2026-10-01',
    certificationStatus: 'Compliant',
    auditor: 'DPO Interne',
  },
  {
    id: 'nist',
    name: 'NIST CSF',
    version: '2.0',
    totalControls: 106,
    compliant: 67,
    partial: 25,
    gap: 14,
    na: 0,
    percentage: 71,
    lastAudit: '2026-03-15',
    nextAudit: '2027-03-15',
    certificationStatus: 'Monitoring',
    auditor: 'Internal',
  },
  {
    id: 'cis',
    name: 'CIS Controls',
    version: 'v8',
    totalControls: 153,
    compliant: 98,
    partial: 38,
    gap: 17,
    na: 0,
    percentage: 75,
    lastAudit: '2026-02-01',
    nextAudit: '2027-02-01',
    certificationStatus: 'Monitoring',
    auditor: 'Internal',
  },
  {
    id: 'soc2',
    name: 'SOC 2',
    version: 'Type II',
    totalControls: 64,
    compliant: 38,
    partial: 16,
    gap: 10,
    na: 0,
    percentage: 70,
    lastAudit: '2025-12-01',
    nextAudit: '2026-12-01',
    certificationStatus: 'In Progress',
    auditor: 'Deloitte',
  },
];

export const mockControls = [
  { id: 'C-001', title: 'Information Security Policy', domain: 'Governance', status: 'implemented', effectiveness: 4, frameworks: ['ISO 27001', 'NIS2', 'SOC 2'], owner: 'Alexandre Dubois', lastReview: '2026-03-01', nextReview: '2027-03-01' },
  { id: 'C-002', title: 'Risk Management Framework', domain: 'Risk Management', status: 'implemented', effectiveness: 3, frameworks: ['ISO 27001', 'NIST CSF', 'DORA'], owner: 'Alexandre Dubois', lastReview: '2026-02-15', nextReview: '2027-02-15' },
  { id: 'C-003', title: 'Asset Inventory Management', domain: 'Asset Management', status: 'partial', effectiveness: 2, frameworks: ['ISO 27001', 'CIS Controls'], owner: 'Thomas Bernard', lastReview: '2026-01-10', nextReview: '2026-07-10' },
  { id: 'C-004', title: 'Access Control Policy', domain: 'Identity & Access', status: 'implemented', effectiveness: 4, frameworks: ['ISO 27001', 'SOC 2', 'CIS Controls'], owner: 'Thomas Bernard', lastReview: '2026-04-01', nextReview: '2027-04-01' },
  { id: 'C-005', title: 'Multi-Factor Authentication', domain: 'Identity & Access', status: 'implemented', effectiveness: 5, frameworks: ['ISO 27001', 'NIST CSF', 'CIS Controls', 'SOC 2'], owner: 'Thomas Bernard', lastReview: '2026-05-01', nextReview: '2027-05-01' },
  { id: 'C-006', title: 'Vulnerability Management Program', domain: 'Security Operations', status: 'partial', effectiveness: 3, frameworks: ['ISO 27001', 'CIS Controls', 'NIST CSF'], owner: 'Camille Rousseau', lastReview: '2026-03-15', nextReview: '2026-09-15' },
  { id: 'C-007', title: 'Security Incident Management', domain: 'Incident Response', status: 'implemented', effectiveness: 4, frameworks: ['ISO 27001', 'NIS2', 'DORA', 'NIST CSF'], owner: 'Alexandre Dubois', lastReview: '2026-04-10', nextReview: '2027-04-10' },
  { id: 'C-008', title: 'Third-Party Risk Assessment', domain: 'Third Party Risk', status: 'partial', effectiveness: 2, frameworks: ['ISO 27001', 'NIS2', 'DORA', 'SOC 2'], owner: 'Sophie Laurent', lastReview: '2026-02-01', nextReview: '2026-08-01' },
  { id: 'C-009', title: 'Data Classification Policy', domain: 'Data Protection', status: 'implemented', effectiveness: 4, frameworks: ['ISO 27001', 'RGPD', 'SOC 2'], owner: 'Camille Rousseau', lastReview: '2026-03-20', nextReview: '2027-03-20' },
  { id: 'C-010', title: 'Business Continuity Plan', domain: 'Business Continuity', status: 'partial', effectiveness: 3, frameworks: ['ISO 27001', 'DORA', 'NIST CSF'], owner: 'Alexandre Dubois', lastReview: '2026-01-15', nextReview: '2026-07-15' },
  { id: 'C-011', title: 'Privileged Access Management', domain: 'Identity & Access', status: 'partial', effectiveness: 2, frameworks: ['ISO 27001', 'CIS Controls', 'SOC 2'], owner: 'Thomas Bernard', lastReview: '2026-02-20', nextReview: '2026-08-20' },
  { id: 'C-012', title: 'Identity Lifecycle Management', domain: 'Identity & Access', status: 'implemented', effectiveness: 4, frameworks: ['ISO 27001', 'NIST CSF'], owner: 'Thomas Bernard', lastReview: '2026-04-05', nextReview: '2027-04-05' },
  { id: 'C-013', title: 'Security Awareness Training', domain: 'Awareness & Training', status: 'partial', effectiveness: 3, frameworks: ['ISO 27001', 'NIS2', 'SOC 2'], owner: 'Camille Rousseau', lastReview: '2026-03-01', nextReview: '2026-09-01' },
  { id: 'C-014', title: 'Endpoint Detection & Response (EDR)', domain: 'Security Operations', status: 'implemented', effectiveness: 4, frameworks: ['CIS Controls', 'NIST CSF'], owner: 'Camille Rousseau', lastReview: '2026-05-01', nextReview: '2027-05-01' },
  { id: 'C-015', title: 'Network Segmentation', domain: 'Security Operations', status: 'implemented', effectiveness: 4, frameworks: ['ISO 27001', 'CIS Controls', 'NIST CSF'], owner: 'Thomas Bernard', lastReview: '2026-04-15', nextReview: '2027-04-15' },
  { id: 'C-016', title: 'Cloud Security Posture Management', domain: 'Cloud Security', status: 'partial', effectiveness: 2, frameworks: ['CIS Controls', 'NIST CSF', 'SOC 2'], owner: 'Sophie Laurent', lastReview: '2026-02-10', nextReview: '2026-08-10' },
  { id: 'C-017', title: 'Data Encryption at Rest', domain: 'Data Protection', status: 'implemented', effectiveness: 5, frameworks: ['ISO 27001', 'RGPD', 'SOC 2'], owner: 'Thomas Bernard', lastReview: '2026-04-20', nextReview: '2027-04-20' },
  { id: 'C-018', title: 'Data Encryption in Transit', domain: 'Data Protection', status: 'implemented', effectiveness: 5, frameworks: ['ISO 27001', 'RGPD', 'SOC 2'], owner: 'Thomas Bernard', lastReview: '2026-04-20', nextReview: '2027-04-20' },
  { id: 'C-019', title: 'SIEM & Log Management', domain: 'Security Operations', status: 'implemented', effectiveness: 3, frameworks: ['ISO 27001', 'NIS2', 'CIS Controls'], owner: 'Camille Rousseau', lastReview: '2026-03-10', nextReview: '2026-09-10' },
  { id: 'C-020', title: 'Penetration Testing Program', domain: 'Security Operations', status: 'partial', effectiveness: 3, frameworks: ['ISO 27001', 'NIS2', 'DORA'], owner: 'Sophie Laurent', lastReview: '2026-01-20', nextReview: '2026-07-20' },
];

export const mockEvidences = [
  { id: 'E-001', title: 'Information Security Policy v3.2', type: 'Policy', control: 'C-001', framework: 'ISO 27001', status: 'accepted', uploadedBy: 'Alexandre Dubois', uploadedAt: '2026-03-01', fileSize: '245 KB', reviewer: 'Camille Rousseau', reviewedAt: '2026-03-05' },
  { id: 'E-002', title: 'MFA Deployment Screenshot', type: 'Screenshot', control: 'C-005', framework: 'ISO 27001', status: 'accepted', uploadedBy: 'Thomas Bernard', uploadedAt: '2026-04-15', fileSize: '1.2 MB', reviewer: 'Camille Rousseau', reviewedAt: '2026-04-16' },
  { id: 'E-003', title: 'Q1 2026 Vulnerability Scan Report', type: 'Report', control: 'C-006', framework: 'CIS Controls', status: 'reviewed', uploadedBy: 'Camille Rousseau', uploadedAt: '2026-04-01', fileSize: '3.8 MB', reviewer: 'Alexandre Dubois', reviewedAt: '2026-04-03' },
  { id: 'E-004', title: 'Third-Party Risk Assessment - Accenture', type: 'Assessment', control: 'C-008', framework: 'ISO 27001', status: 'provided', uploadedBy: 'Sophie Laurent', uploadedAt: '2026-04-20', fileSize: '890 KB', reviewer: null, reviewedAt: null },
  { id: 'E-005', title: 'Business Continuity Test Results 2026', type: 'Test Report', control: 'C-010', framework: 'DORA', status: 'requested', uploadedBy: null, uploadedAt: null, fileSize: null, reviewer: null, reviewedAt: null },
  { id: 'E-006', title: 'Access Review Certificate Q1 2026', type: 'Certificate', control: 'C-004', framework: 'ISO 27001', status: 'accepted', uploadedBy: 'Thomas Bernard', uploadedAt: '2026-04-05', fileSize: '156 KB', reviewer: 'Camille Rousseau', reviewedAt: '2026-04-07' },
  { id: 'E-007', title: 'Employee Security Training Completion Report', type: 'Report', control: 'C-013', framework: 'NIS2', status: 'reviewed', uploadedBy: 'Camille Rousseau', uploadedAt: '2026-03-31', fileSize: '2.1 MB', reviewer: 'Alexandre Dubois', reviewedAt: '2026-04-02' },
  { id: 'E-008', title: 'SOC 2 Type II Audit Report 2025', type: 'Audit Report', control: 'C-001', framework: 'SOC 2', status: 'accepted', uploadedBy: 'Sophie Laurent', uploadedAt: '2026-01-15', fileSize: '12.4 MB', reviewer: 'Alexandre Dubois', reviewedAt: '2026-01-20' },
  { id: 'E-009', title: 'Network Diagram - Segmentation Evidence', type: 'Diagram', control: 'C-015', framework: 'CIS Controls', status: 'accepted', uploadedBy: 'Thomas Bernard', uploadedAt: '2026-04-10', fileSize: '560 KB', reviewer: 'Camille Rousseau', reviewedAt: '2026-04-12' },
  { id: 'E-010', title: 'Incident Response Plan v2.1', type: 'Plan', control: 'C-007', framework: 'NIS2', status: 'rejected', uploadedBy: 'Alexandre Dubois', uploadedAt: '2026-03-20', fileSize: '890 KB', reviewer: 'Camille Rousseau', reviewedAt: '2026-03-22' },
];

export const mockPolicies = [
  { id: 'P-001', title: 'Information Security Policy', version: '3.2', status: 'approved', owner: 'Alexandre Dubois', approvedBy: 'Nicolas Martin', lastReview: '2026-03-01', nextReview: '2027-03-01', framework: 'ISO 27001' },
  { id: 'P-002', title: 'Access Control Policy', version: '2.4', status: 'approved', owner: 'Thomas Bernard', approvedBy: 'Alexandre Dubois', lastReview: '2026-04-01', nextReview: '2027-04-01', framework: 'ISO 27001' },
  { id: 'P-003', title: 'Incident Response Plan', version: '2.1', status: 'under_review', owner: 'Alexandre Dubois', approvedBy: null, lastReview: '2026-03-15', nextReview: '2026-09-15', framework: 'NIS2' },
  { id: 'P-004', title: 'Business Continuity Plan', version: '1.8', status: 'approved', owner: 'Alexandre Dubois', approvedBy: 'Nicolas Martin', lastReview: '2026-01-15', nextReview: '2026-07-15', framework: 'DORA' },
  { id: 'P-005', title: 'Data Protection Policy', version: '2.0', status: 'approved', owner: 'Camille Rousseau', approvedBy: 'Alexandre Dubois', lastReview: '2026-04-01', nextReview: '2027-04-01', framework: 'RGPD' },
  { id: 'P-006', title: 'Vendor Security Policy', version: '1.5', status: 'under_review', owner: 'Sophie Laurent', approvedBy: null, lastReview: '2026-02-01', nextReview: '2026-08-01', framework: 'ISO 27001' },
  { id: 'P-007', title: 'Acceptable Use Policy', version: '3.0', status: 'approved', owner: 'Camille Rousseau', approvedBy: 'Nicolas Martin', lastReview: '2026-03-20', nextReview: '2027-03-20', framework: 'ISO 27001' },
  { id: 'P-008', title: 'Cloud Security Policy', version: '1.2', status: 'draft', owner: 'Sophie Laurent', approvedBy: null, lastReview: null, nextReview: null, framework: 'CIS Controls' },
  { id: 'P-009', title: 'Cryptography Policy', version: '2.1', status: 'approved', owner: 'Thomas Bernard', approvedBy: 'Alexandre Dubois', lastReview: '2026-04-20', nextReview: '2027-04-20', framework: 'ISO 27001' },
  { id: 'P-010', title: 'DORA ICT Risk Management Policy', version: '1.0', status: 'draft', owner: 'Alexandre Dubois', approvedBy: null, lastReview: null, nextReview: null, framework: 'DORA' },
];

export const mockIncidents = [
  { id: 'INC-001', title: 'Phishing campaign targeting finance team', severity: 'high', status: 'resolved', category: 'Social Engineering', reportedAt: '2026-04-10', resolvedAt: '2026-04-12', affectedSystems: 'Email', affectedUsers: 12, reportedBy: 'Thomas Bernard', assignedTo: 'Camille Rousseau', rootCause: 'Targeted spear-phishing email bypassed email gateway filters', impact: 'No data breach; 3 credential resets required', lessons: 'Improve email gateway rules; update awareness training content' },
  { id: 'INC-002', title: 'Unauthorized access attempt on VPN', severity: 'medium', status: 'investigating', category: 'Unauthorized Access', reportedAt: '2026-05-01', resolvedAt: null, affectedSystems: 'VPN Gateway', affectedUsers: 0, reportedBy: 'SIEM Alert', assignedTo: 'Thomas Bernard', rootCause: 'Under investigation - credential stuffing suspected', impact: 'No successful breach confirmed', lessons: null },
  { id: 'INC-003', title: 'Critical vulnerability in Apache Log4j (legacy system)', severity: 'critical', status: 'resolved', category: 'Vulnerability', reportedAt: '2026-03-15', resolvedAt: '2026-03-20', affectedSystems: 'Legacy Reporting App', affectedUsers: 0, reportedBy: 'Camille Rousseau', assignedTo: 'Thomas Bernard', rootCause: 'Unpatched legacy application discovered during vulnerability scan', impact: 'System isolated during patching; no exploitation detected', lessons: 'Accelerate legacy system patching; monthly vulnerability scans' },
  { id: 'INC-004', title: 'Sensitive data inadvertently shared via email', severity: 'low', status: 'resolved', category: 'Data Leak', reportedAt: '2026-04-25', resolvedAt: '2026-04-26', affectedSystems: 'Email', affectedUsers: 2, reportedBy: 'Isabelle Petit', assignedTo: 'Camille Rousseau', rootCause: 'User error - incorrect email recipient for confidential document', impact: 'Single confidential document sent to wrong external party; document deleted', lessons: 'Implement DLP email rules; reinforce data handling training' },
  { id: 'INC-005', title: 'Third-party vendor API exposed sensitive credentials', severity: 'high', status: 'remediated', category: 'Third-Party', reportedAt: '2026-04-05', resolvedAt: '2026-04-08', affectedSystems: 'API Gateway', affectedUsers: 0, reportedBy: 'Sophie Laurent', assignedTo: 'Thomas Bernard', rootCause: 'Vendor hardcoded credentials in shared repository', impact: 'Credentials rotated immediately; no unauthorized access detected', lessons: 'Mandatory vendor security assessment before integration' },
];

export const mockActionPlans = [
  { id: 'AP-001', title: 'Deploy PAM solution for privileged accounts', description: 'Implement CyberArk PAM to manage and monitor all privileged access.', status: 'in_progress', priority: 'critical', owner: 'Thomas Bernard', dueDate: '2026-06-30', progress: 45, linkedRisk: 'R-004', linkedControl: 'C-011', estimatedEffort: '120h', budget: 85000 },
  { id: 'AP-002', title: 'Complete DORA ICT incident reporting procedures', description: 'Develop and validate DORA-compliant incident classification, notification and reporting workflows.', status: 'in_progress', priority: 'critical', owner: 'Alexandre Dubois', dueDate: '2026-07-01', progress: 30, linkedRisk: 'R-003', linkedControl: 'C-007', estimatedEffort: '80h', budget: 20000 },
  { id: 'AP-003', title: 'Vendor security questionnaire rollout', description: 'Deploy standardized security questionnaire to all Tier 1 and Tier 2 vendors.', status: 'in_progress', priority: 'high', owner: 'Sophie Laurent', dueDate: '2026-05-31', progress: 70, linkedRisk: 'R-002', linkedControl: 'C-008', estimatedEffort: '40h', budget: 0 },
  { id: 'AP-004', title: 'Business continuity drill - payment systems', description: 'Execute full BCP failover test for payment processing infrastructure.', status: 'todo', priority: 'high', owner: 'Alexandre Dubois', dueDate: '2026-08-31', progress: 0, linkedRisk: 'R-006', linkedControl: 'C-010', estimatedEffort: '60h', budget: 15000 },
  { id: 'AP-005', title: 'Security awareness training Q2 rollout', description: 'Launch mandatory Q2 security awareness training for all 1,200 employees.', status: 'in_progress', priority: 'medium', owner: 'Camille Rousseau', dueDate: '2026-06-01', progress: 55, linkedRisk: 'R-007', linkedControl: 'C-013', estimatedEffort: '30h', budget: 12000 },
  { id: 'AP-006', title: 'Cloud CSPM tool deployment', description: 'Deploy Microsoft Defender for Cloud across all Azure subscriptions.', status: 'todo', priority: 'high', owner: 'Sophie Laurent', dueDate: '2026-07-31', progress: 0, linkedRisk: 'R-005', linkedControl: 'C-016', estimatedEffort: '90h', budget: 45000 },
  { id: 'AP-007', title: 'Legacy system patching sprint', description: 'Patch or isolate 8 legacy applications with critical CVEs.', status: 'in_progress', priority: 'high', owner: 'Thomas Bernard', dueDate: '2026-07-31', progress: 25, linkedRisk: 'R-008', linkedControl: 'C-006', estimatedEffort: '200h', budget: 30000 },
  { id: 'AP-008', title: 'ISO 27001 recertification preparation', description: 'Address all non-conformities from internal audit; prepare evidence package.', status: 'todo', priority: 'medium', owner: 'Camille Rousseau', dueDate: '2026-09-30', progress: 0, linkedRisk: null, linkedControl: null, estimatedEffort: '160h', budget: 25000 },
  { id: 'AP-009', title: 'GDPR DSAR workflow automation', description: 'Implement automated data subject request tracking and response system.', status: 'done', priority: 'medium', owner: 'Camille Rousseau', dueDate: '2026-04-30', progress: 100, linkedRisk: 'R-009', linkedControl: 'C-091', estimatedEffort: '50h', budget: 8000 },
  { id: 'AP-010', title: 'NIS2 gap remediation roadmap', description: 'Develop and present to management the NIS2 gap closure plan.', status: 'done', priority: 'critical', owner: 'Alexandre Dubois', dueDate: '2026-04-15', progress: 100, linkedRisk: null, linkedControl: null, estimatedEffort: '40h', budget: 0 },
];

export const mockAssets = [
  { id: 'A-001', name: 'Core Banking Platform', type: 'Application', criticality: 'critical', owner: 'Alexandre Dubois', classification: 'Confidential', dependencies: ['A-005', 'A-007'], riskScore: 88, lastReview: '2026-03-01' },
  { id: 'A-002', name: 'Customer Data Warehouse', type: 'Data Store', criticality: 'critical', owner: 'Thomas Bernard', classification: 'Restricted', dependencies: ['A-001', 'A-008'], riskScore: 92, lastReview: '2026-04-01' },
  { id: 'A-003', name: 'Active Directory', type: 'Infrastructure', criticality: 'critical', owner: 'Thomas Bernard', classification: 'Confidential', dependencies: ['A-007'], riskScore: 85, lastReview: '2026-03-15' },
  { id: 'A-004', name: 'Payment Processing Systems', type: 'Application', criticality: 'critical', owner: 'Alexandre Dubois', classification: 'Restricted', dependencies: ['A-001', 'A-005'], riskScore: 90, lastReview: '2026-02-01' },
  { id: 'A-005', name: 'Azure Cloud Infrastructure', type: 'Cloud Platform', criticality: 'high', owner: 'Sophie Laurent', classification: 'Confidential', dependencies: [], riskScore: 72, lastReview: '2026-04-10' },
  { id: 'A-006', name: 'Email Platform (M365)', type: 'SaaS', criticality: 'high', owner: 'Thomas Bernard', classification: 'Internal', dependencies: ['A-003'], riskScore: 65, lastReview: '2026-04-20' },
  { id: 'A-007', name: 'Corporate Network Infrastructure', type: 'Infrastructure', criticality: 'high', owner: 'Thomas Bernard', classification: 'Confidential', dependencies: [], riskScore: 70, lastReview: '2026-03-20' },
  { id: 'A-008', name: 'CRM System', type: 'Application', criticality: 'medium', owner: 'Camille Rousseau', classification: 'Confidential', dependencies: ['A-002', 'A-003'], riskScore: 55, lastReview: '2026-02-15' },
];

export const mockThirdParties = [
  { id: 'TP-001', name: 'Microsoft Azure', category: 'Cloud Infrastructure', tier: 1, riskScore: 35, status: 'approved', dpaStatus: 'signed', lastAssessment: '2026-04-01', nextAssessment: '2027-04-01', contact: 'Microsoft TAM', spend: 2400000 },
  { id: 'TP-002', name: 'Accenture', category: 'IT Services', tier: 1, riskScore: 62, status: 'under_review', dpaStatus: 'signed', lastAssessment: '2026-02-15', nextAssessment: '2026-08-15', contact: 'Jean-Pierre Leclerc', spend: 1800000 },
  { id: 'TP-003', name: 'Temenos (Core Banking)', category: 'SaaS - Core System', tier: 1, riskScore: 55, status: 'approved', dpaStatus: 'signed', lastAssessment: '2026-01-20', nextAssessment: '2026-07-20', contact: 'Temenos Support', spend: 3200000 },
  { id: 'TP-004', name: 'Salesforce', category: 'SaaS - CRM', tier: 2, riskScore: 40, status: 'approved', dpaStatus: 'signed', lastAssessment: '2026-03-01', nextAssessment: '2027-03-01', contact: 'SF Account Manager', spend: 480000 },
  { id: 'TP-005', name: 'Deloitte (Audit)', category: 'Audit & Consulting', tier: 2, riskScore: 30, status: 'approved', dpaStatus: 'signed', lastAssessment: '2025-12-01', nextAssessment: '2026-12-01', contact: 'Marie Lefebvre', spend: 950000 },
  { id: 'TP-006', name: 'SecureWorks (SOC)', category: 'Managed Security', tier: 1, riskScore: 48, status: 'approved', dpaStatus: 'signed', lastAssessment: '2026-04-15', nextAssessment: '2027-04-15', contact: 'SOC Manager', spend: 720000 },
  { id: 'TP-007', name: 'Infotel', category: 'IT Development', tier: 2, riskScore: 70, status: 'flagged', dpaStatus: 'pending', lastAssessment: '2026-01-10', nextAssessment: '2026-07-10', contact: 'Pierre Duval', spend: 340000 },
  { id: 'TP-008', name: 'Swift', category: 'Financial Network', tier: 1, riskScore: 25, status: 'approved', dpaStatus: 'signed', lastAssessment: '2026-03-20', nextAssessment: '2027-03-20', contact: 'Swift CSP', spend: 180000 },
];

export const mockProjects = [
  { id: 'PRJ-001', title: 'ISO 27001 Recertification', category: 'Compliance', priority: 'critical', status: 'in_progress', owner: 'Camille Rousseau', startDate: '2026-03-01', endDate: '2026-11-30', progress: 38, budget: 120000, maturityImpact: '+0.8', complianceImpact: 'ISO 27001 +15%' },
  { id: 'PRJ-002', title: 'DORA ICT Resilience Program', category: 'Regulatory', priority: 'critical', status: 'in_progress', owner: 'Alexandre Dubois', startDate: '2026-02-01', endDate: '2026-12-31', progress: 42, budget: 380000, maturityImpact: '+1.2', complianceImpact: 'DORA +25%' },
  { id: 'PRJ-003', title: 'PAM Implementation', category: 'Security', priority: 'high', status: 'in_progress', owner: 'Thomas Bernard', startDate: '2026-04-01', endDate: '2026-08-31', progress: 45, budget: 85000, maturityImpact: '+0.5', complianceImpact: 'IAM Domain +30%' },
  { id: 'PRJ-004', title: 'Zero Trust Architecture Migration', category: 'Architecture', priority: 'high', status: 'planning', owner: 'Sophie Laurent', startDate: '2026-07-01', endDate: '2027-06-30', progress: 5, budget: 650000, maturityImpact: '+1.5', complianceImpact: 'Multiple +20%' },
  { id: 'PRJ-005', title: 'Cloud Security Hardening', category: 'Cloud', priority: 'high', status: 'in_progress', owner: 'Sophie Laurent', startDate: '2026-04-15', endDate: '2026-09-30', progress: 28, budget: 75000, maturityImpact: '+0.6', complianceImpact: 'Cloud Domain +25%' },
  { id: 'PRJ-006', title: 'NIS2 Gap Remediation', category: 'Regulatory', priority: 'high', status: 'in_progress', owner: 'Alexandre Dubois', startDate: '2026-03-01', endDate: '2026-10-17', progress: 35, budget: 95000, maturityImpact: '+0.7', complianceImpact: 'NIS2 +30%' },
  { id: 'PRJ-007', title: 'SOC 2 Type II Preparation', category: 'Compliance', priority: 'medium', status: 'planning', owner: 'Camille Rousseau', startDate: '2026-06-01', endDate: '2026-12-31', progress: 0, budget: 60000, maturityImpact: '+0.4', complianceImpact: 'SOC 2 +20%' },
  { id: 'PRJ-008', title: 'Security Awareness Platform', category: 'Training', priority: 'medium', status: 'in_progress', owner: 'Camille Rousseau', startDate: '2026-02-15', endDate: '2026-06-30', progress: 60, budget: 35000, maturityImpact: '+0.3', complianceImpact: 'Training Domain +40%' },
];

export const mockMaturityDomains = [
  { domain: 'Governance', score: 3.8, target: 4.5, weight: 15 },
  { domain: 'Risk Management', score: 3.2, target: 4.0, weight: 15 },
  { domain: 'Asset Management', score: 2.9, target: 4.0, weight: 10 },
  { domain: 'Identity & Access', score: 3.5, target: 4.5, weight: 12 },
  { domain: 'Security Operations', score: 3.1, target: 4.5, weight: 15 },
  { domain: 'Incident Response', score: 3.4, target: 4.0, weight: 10 },
  { domain: 'Business Continuity', score: 2.7, target: 4.0, weight: 8 },
  { domain: 'Third Party Risk', score: 2.5, target: 4.0, weight: 8 },
  { domain: 'Data Protection', score: 3.6, target: 4.5, weight: 7 },
];

export const mockDashboardKPIs = {
  cyberMaturityScore: 3.2,
  cyberMaturityTrend: +0.3,
  complianceReadiness: 68,
  complianceReadinessTrend: +4,
  criticalRisks: 7,
  criticalRisksTrend: -2,
  overdueActions: 12,
  overdueActionsTrend: +3,
  auditReadiness: 61,
  auditReadinessTrend: +8,
  controlCoverage: 74,
  openIncidents: 4,
  thirdPartyRisk: 'Medium',
  actionPlanProgress: 58,
  isoReadiness: 68,
  nis2Readiness: 54,
  doraReadiness: 61,
  rgpdReadiness: 82,
};

export const mockAuditLogs = [
  { id: 'LOG-001', action: 'Risk created', entity: 'R-001', user: 'Alexandre Dubois', timestamp: '2026-05-08T14:23:00Z', details: 'New critical risk created: Ransomware attack on core banking' },
  { id: 'LOG-002', action: 'Evidence uploaded', entity: 'E-003', user: 'Camille Rousseau', timestamp: '2026-05-08T11:15:00Z', details: 'Q1 2026 Vulnerability Scan Report uploaded' },
  { id: 'LOG-003', action: 'Policy approved', entity: 'P-005', user: 'Alexandre Dubois', timestamp: '2026-05-07T16:45:00Z', details: 'Data Protection Policy v2.0 approved' },
  { id: 'LOG-004', action: 'Compliance status updated', entity: 'iso27001', user: 'Camille Rousseau', timestamp: '2026-05-07T10:30:00Z', details: 'ISO 27001 A.5.1 control status changed to Compliant' },
  { id: 'LOG-005', action: 'Report exported', entity: 'RPT-004', user: 'Sophie Laurent', timestamp: '2026-05-06T09:00:00Z', details: 'Executive compliance report exported to PDF' },
  { id: 'LOG-006', action: 'Incident created', entity: 'INC-002', user: 'SIEM Alert', timestamp: '2026-05-01T08:42:00Z', details: 'Unauthorized VPN access attempt detected' },
  { id: 'LOG-007', action: 'Action plan updated', entity: 'AP-003', user: 'Sophie Laurent', timestamp: '2026-05-05T14:00:00Z', details: 'Progress updated: 50% → 70%' },
  { id: 'LOG-008', action: 'User login', entity: 'u-1', user: 'Alexandre Dubois', timestamp: '2026-05-09T08:01:00Z', details: 'Successful login from 192.168.1.45' },
];

export const mockRiskMatrixData = [
  [0, 1, 2, 1, 0],
  [1, 2, 3, 2, 1],
  [1, 2, 4, 3, 2],
  [0, 1, 2, 3, 2],
  [0, 0, 1, 2, 1],
];

export const mockComplianceTimeline = [
  { date: '2026-01', iso: 60, nis2: 42, dora: 48, rgpd: 74 },
  { date: '2026-02', iso: 62, nis2: 45, dora: 51, rgpd: 76 },
  { date: '2026-03', iso: 65, nis2: 48, dora: 55, rgpd: 78 },
  { date: '2026-04', iso: 66, nis2: 51, dora: 58, rgpd: 80 },
  { date: '2026-05', iso: 68, nis2: 54, dora: 61, rgpd: 82 },
];
